/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_IntersectionReferenceID_H_
#define	_carma_j2735_IntersectionReferenceID_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_RoadRegulatorID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_IntersectionID.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_IntersectionReferenceID */
typedef struct carma_j2735_IntersectionReferenceID {
	carma_j2735_RoadRegulatorID_t	*region;	/* OPTIONAL */
	carma_j2735_IntersectionID_t	 id;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_IntersectionReferenceID_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_IntersectionReferenceID;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_IntersectionReferenceID_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_IntersectionReferenceID_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_IntersectionReferenceID_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
