/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_TimeConfidence_H_
#define	_carma_j2735_TimeConfidence_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_TimeConfidence {
	carma_j2735_TimeConfidence_unavailable	= 0,
	carma_j2735_TimeConfidence_time_100_000	= 1,
	carma_j2735_TimeConfidence_time_050_000	= 2,
	carma_j2735_TimeConfidence_time_020_000	= 3,
	carma_j2735_TimeConfidence_time_010_000	= 4,
	carma_j2735_TimeConfidence_time_002_000	= 5,
	carma_j2735_TimeConfidence_time_001_000	= 6,
	carma_j2735_TimeConfidence_time_000_500	= 7,
	carma_j2735_TimeConfidence_time_000_200	= 8,
	carma_j2735_TimeConfidence_time_000_100	= 9,
	carma_j2735_TimeConfidence_time_000_050	= 10,
	carma_j2735_TimeConfidence_time_000_020	= 11,
	carma_j2735_TimeConfidence_time_000_010	= 12,
	carma_j2735_TimeConfidence_time_000_005	= 13,
	carma_j2735_TimeConfidence_time_000_002	= 14,
	carma_j2735_TimeConfidence_time_000_001	= 15,
	carma_j2735_TimeConfidence_time_000_000_5	= 16,
	carma_j2735_TimeConfidence_time_000_000_2	= 17,
	carma_j2735_TimeConfidence_time_000_000_1	= 18,
	carma_j2735_TimeConfidence_time_000_000_05	= 19,
	carma_j2735_TimeConfidence_time_000_000_02	= 20,
	carma_j2735_TimeConfidence_time_000_000_01	= 21,
	carma_j2735_TimeConfidence_time_000_000_005	= 22,
	carma_j2735_TimeConfidence_time_000_000_002	= 23,
	carma_j2735_TimeConfidence_time_000_000_001	= 24,
	carma_j2735_TimeConfidence_time_000_000_000_5	= 25,
	carma_j2735_TimeConfidence_time_000_000_000_2	= 26,
	carma_j2735_TimeConfidence_time_000_000_000_1	= 27,
	carma_j2735_TimeConfidence_time_000_000_000_05	= 28,
	carma_j2735_TimeConfidence_time_000_000_000_02	= 29,
	carma_j2735_TimeConfidence_time_000_000_000_01	= 30,
	carma_j2735_TimeConfidence_time_000_000_000_005	= 31,
	carma_j2735_TimeConfidence_time_000_000_000_002	= 32,
	carma_j2735_TimeConfidence_time_000_000_000_001	= 33,
	carma_j2735_TimeConfidence_time_000_000_000_000_5	= 34,
	carma_j2735_TimeConfidence_time_000_000_000_000_2	= 35,
	carma_j2735_TimeConfidence_time_000_000_000_000_1	= 36,
	carma_j2735_TimeConfidence_time_000_000_000_000_05	= 37,
	carma_j2735_TimeConfidence_time_000_000_000_000_02	= 38,
	carma_j2735_TimeConfidence_time_000_000_000_000_01	= 39
} e_carma_j2735_TimeConfidence;

/* carma_j2735_TimeConfidence */
typedef long	 carma_j2735_TimeConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_TimeConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_TimeConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_TimeConfidence_specs_1;
asn_struct_free_f carma_j2735_TimeConfidence_free;
asn_struct_print_f carma_j2735_TimeConfidence_print;
asn_constr_check_f carma_j2735_TimeConfidence_constraint;
per_type_decoder_f carma_j2735_TimeConfidence_decode_uper;
per_type_encoder_f carma_j2735_TimeConfidence_encode_uper;
per_type_decoder_f carma_j2735_TimeConfidence_decode_aper;
per_type_encoder_f carma_j2735_TimeConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_TimeConfidence_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
