/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_HeadingSlice_H_
#define	_carma_j2735_HeadingSlice_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_HeadingSlice {
	carma_j2735_HeadingSlice_from000_0to022_5degrees	= 0,
	carma_j2735_HeadingSlice_from022_5to045_0degrees	= 1,
	carma_j2735_HeadingSlice_from045_0to067_5degrees	= 2,
	carma_j2735_HeadingSlice_from067_5to090_0degrees	= 3,
	carma_j2735_HeadingSlice_from090_0to112_5degrees	= 4,
	carma_j2735_HeadingSlice_from112_5to135_0degrees	= 5,
	carma_j2735_HeadingSlice_from135_0to157_5degrees	= 6,
	carma_j2735_HeadingSlice_from157_5to180_0degrees	= 7,
	carma_j2735_HeadingSlice_from180_0to202_5degrees	= 8,
	carma_j2735_HeadingSlice_from202_5to225_0degrees	= 9,
	carma_j2735_HeadingSlice_from225_0to247_5degrees	= 10,
	carma_j2735_HeadingSlice_from247_5to270_0degrees	= 11,
	carma_j2735_HeadingSlice_from270_0to292_5degrees	= 12,
	carma_j2735_HeadingSlice_from292_5to315_0degrees	= 13,
	carma_j2735_HeadingSlice_from315_0to337_5degrees	= 14,
	carma_j2735_HeadingSlice_from337_5to360_0degrees	= 15
} e_carma_j2735_HeadingSlice;

/* carma_j2735_HeadingSlice */
typedef BIT_STRING_t	 carma_j2735_HeadingSlice_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_HeadingSlice_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_HeadingSlice;
asn_struct_free_f carma_j2735_HeadingSlice_free;
asn_struct_print_f carma_j2735_HeadingSlice_print;
asn_constr_check_f carma_j2735_HeadingSlice_constraint;
per_type_decoder_f carma_j2735_HeadingSlice_decode_uper;
per_type_encoder_f carma_j2735_HeadingSlice_encode_uper;
per_type_decoder_f carma_j2735_HeadingSlice_decode_aper;
per_type_encoder_f carma_j2735_HeadingSlice_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_HeadingSlice_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
