/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_LaneAttributes_Vehicle_H_
#define	_carma_j2735_LaneAttributes_Vehicle_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_LaneAttributes_Vehicle {
	carma_j2735_LaneAttributes_Vehicle_isVehicleRevocableLane	= 0,
	carma_j2735_LaneAttributes_Vehicle_isVehicleFlyOverLane	= 1,
	carma_j2735_LaneAttributes_Vehicle_hovLaneUseOnly	= 2,
	carma_j2735_LaneAttributes_Vehicle_restrictedToBusUse	= 3,
	carma_j2735_LaneAttributes_Vehicle_restrictedToTaxiUse	= 4,
	carma_j2735_LaneAttributes_Vehicle_restrictedFromPublicUse	= 5,
	carma_j2735_LaneAttributes_Vehicle_hasIRbeaconCoverage	= 6,
	carma_j2735_LaneAttributes_Vehicle_permissionOnRequest	= 7
} e_carma_j2735_LaneAttributes_Vehicle;

/* carma_j2735_LaneAttributes-Vehicle */
typedef BIT_STRING_t	 carma_j2735_LaneAttributes_Vehicle_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_LaneAttributes_Vehicle_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_LaneAttributes_Vehicle;
asn_struct_free_f carma_j2735_LaneAttributes_Vehicle_free;
asn_struct_print_f carma_j2735_LaneAttributes_Vehicle_print;
asn_constr_check_f carma_j2735_LaneAttributes_Vehicle_constraint;
per_type_decoder_f carma_j2735_LaneAttributes_Vehicle_decode_uper;
per_type_encoder_f carma_j2735_LaneAttributes_Vehicle_encode_uper;
per_type_decoder_f carma_j2735_LaneAttributes_Vehicle_decode_aper;
per_type_encoder_f carma_j2735_LaneAttributes_Vehicle_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_LaneAttributes_Vehicle_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
