/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VehicleType_H_
#define	_carma_j2735_VehicleType_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_VehicleType {
	carma_j2735_VehicleType_none	= 0,
	carma_j2735_VehicleType_unknown	= 1,
	carma_j2735_VehicleType_special	= 2,
	carma_j2735_VehicleType_moto	= 3,
	carma_j2735_VehicleType_car	= 4,
	carma_j2735_VehicleType_carOther	= 5,
	carma_j2735_VehicleType_bus	= 6,
	carma_j2735_VehicleType_axleCnt2	= 7,
	carma_j2735_VehicleType_axleCnt3	= 8,
	carma_j2735_VehicleType_axleCnt4	= 9,
	carma_j2735_VehicleType_axleCnt4Trailer	= 10,
	carma_j2735_VehicleType_axleCnt5Trailer	= 11,
	carma_j2735_VehicleType_axleCnt6Trailer	= 12,
	carma_j2735_VehicleType_axleCnt5MultiTrailer	= 13,
	carma_j2735_VehicleType_axleCnt6MultiTrailer	= 14,
	carma_j2735_VehicleType_axleCnt7MultiTrailer	= 15
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_VehicleType;

/* carma_j2735_VehicleType */
typedef long	 carma_j2735_VehicleType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_VehicleType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VehicleType;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_VehicleType_specs_1;
asn_struct_free_f carma_j2735_VehicleType_free;
asn_struct_print_f carma_j2735_VehicleType_print;
asn_constr_check_f carma_j2735_VehicleType_constraint;
per_type_decoder_f carma_j2735_VehicleType_decode_uper;
per_type_encoder_f carma_j2735_VehicleType_encode_uper;
per_type_decoder_f carma_j2735_VehicleType_decode_aper;
per_type_encoder_f carma_j2735_VehicleType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_VehicleType_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
