/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ResponderGroupAffected_H_
#define	_carma_j2735_ResponderGroupAffected_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ResponderGroupAffected {
	carma_j2735_ResponderGroupAffected_emergency_vehicle_units	= 9729,
	carma_j2735_ResponderGroupAffected_federal_law_enforcement_units	= 9730,
	carma_j2735_ResponderGroupAffected_state_police_units	= 9731,
	carma_j2735_ResponderGroupAffected_county_police_units	= 9732,
	carma_j2735_ResponderGroupAffected_local_police_units	= 9733,
	carma_j2735_ResponderGroupAffected_ambulance_units	= 9734,
	carma_j2735_ResponderGroupAffected_rescue_units	= 9735,
	carma_j2735_ResponderGroupAffected_fire_units	= 9736,
	carma_j2735_ResponderGroupAffected_hAZMAT_units	= 9737,
	carma_j2735_ResponderGroupAffected_light_tow_unit	= 9738,
	carma_j2735_ResponderGroupAffected_heavy_tow_unit	= 9739,
	carma_j2735_ResponderGroupAffected_freeway_service_patrols	= 9740,
	carma_j2735_ResponderGroupAffected_transportation_response_units	= 9741,
	carma_j2735_ResponderGroupAffected_private_contractor_response_units	= 9742
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_ResponderGroupAffected;

/* carma_j2735_ResponderGroupAffected */
typedef long	 carma_j2735_ResponderGroupAffected_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_ResponderGroupAffected_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ResponderGroupAffected;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_ResponderGroupAffected_specs_1;
asn_struct_free_f carma_j2735_ResponderGroupAffected_free;
asn_struct_print_f carma_j2735_ResponderGroupAffected_print;
asn_constr_check_f carma_j2735_ResponderGroupAffected_constraint;
per_type_decoder_f carma_j2735_ResponderGroupAffected_decode_uper;
per_type_encoder_f carma_j2735_ResponderGroupAffected_encode_uper;
per_type_decoder_f carma_j2735_ResponderGroupAffected_decode_aper;
per_type_encoder_f carma_j2735_ResponderGroupAffected_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_ResponderGroupAffected_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
