/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VehicleStatusDeviceTypeTag_H_
#define	_carma_j2735_VehicleStatusDeviceTypeTag_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_VehicleStatusDeviceTypeTag {
	carma_j2735_VehicleStatusDeviceTypeTag_unknown	= 0,
	carma_j2735_VehicleStatusDeviceTypeTag_lights	= 1,
	carma_j2735_VehicleStatusDeviceTypeTag_wipers	= 2,
	carma_j2735_VehicleStatusDeviceTypeTag_brakes	= 3,
	carma_j2735_VehicleStatusDeviceTypeTag_stab	= 4,
	carma_j2735_VehicleStatusDeviceTypeTag_trac	= 5,
	carma_j2735_VehicleStatusDeviceTypeTag_abs	= 6,
	carma_j2735_VehicleStatusDeviceTypeTag_sunS	= 7,
	carma_j2735_VehicleStatusDeviceTypeTag_rainS	= 8,
	carma_j2735_VehicleStatusDeviceTypeTag_airTemp	= 9,
	carma_j2735_VehicleStatusDeviceTypeTag_steering	= 10,
	carma_j2735_VehicleStatusDeviceTypeTag_vertAccelThres	= 11,
	carma_j2735_VehicleStatusDeviceTypeTag_vertAccel	= 12,
	carma_j2735_VehicleStatusDeviceTypeTag_hozAccelLong	= 13,
	carma_j2735_VehicleStatusDeviceTypeTag_hozAccelLat	= 14,
	carma_j2735_VehicleStatusDeviceTypeTag_hozAccelCon	= 15,
	carma_j2735_VehicleStatusDeviceTypeTag_accel4way	= 16,
	carma_j2735_VehicleStatusDeviceTypeTag_confidenceSet	= 17,
	carma_j2735_VehicleStatusDeviceTypeTag_obDist	= 18,
	carma_j2735_VehicleStatusDeviceTypeTag_obDirect	= 19,
	carma_j2735_VehicleStatusDeviceTypeTag_yaw	= 20,
	carma_j2735_VehicleStatusDeviceTypeTag_yawRateCon	= 21,
	carma_j2735_VehicleStatusDeviceTypeTag_dateTime	= 22,
	carma_j2735_VehicleStatusDeviceTypeTag_fullPos	= 23,
	carma_j2735_VehicleStatusDeviceTypeTag_position2D	= 24,
	carma_j2735_VehicleStatusDeviceTypeTag_position3D	= 25,
	carma_j2735_VehicleStatusDeviceTypeTag_vehicle	= 26,
	carma_j2735_VehicleStatusDeviceTypeTag_speedHeadC	= 27,
	carma_j2735_VehicleStatusDeviceTypeTag_speedC	= 28
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_VehicleStatusDeviceTypeTag;

/* carma_j2735_VehicleStatusDeviceTypeTag */
typedef long	 carma_j2735_VehicleStatusDeviceTypeTag_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_VehicleStatusDeviceTypeTag_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VehicleStatusDeviceTypeTag;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_VehicleStatusDeviceTypeTag_specs_1;
asn_struct_free_f carma_j2735_VehicleStatusDeviceTypeTag_free;
asn_struct_print_f carma_j2735_VehicleStatusDeviceTypeTag_print;
asn_constr_check_f carma_j2735_VehicleStatusDeviceTypeTag_constraint;
per_type_decoder_f carma_j2735_VehicleStatusDeviceTypeTag_decode_uper;
per_type_encoder_f carma_j2735_VehicleStatusDeviceTypeTag_encode_uper;
per_type_decoder_f carma_j2735_VehicleStatusDeviceTypeTag_decode_aper;
per_type_encoder_f carma_j2735_VehicleStatusDeviceTypeTag_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_VehicleStatusDeviceTypeTag_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
