/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_SignalStatusPackage_H_
#define	_carma_j2735_SignalStatusPackage_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_IntersectionAccessPoint.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MinuteOfTheYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSecond.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PrioritizationResponseStatus.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_SignalRequesterInfo;
struct carma_j2735_IntersectionAccessPoint;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_SignalStatusPackage */
typedef struct carma_j2735_SignalStatusPackage {
	struct carma_j2735_SignalRequesterInfo	*requester;	/* OPTIONAL */
	carma_j2735_IntersectionAccessPoint_t	 inboundOn;
	struct carma_j2735_IntersectionAccessPoint	*outboundOn;	/* OPTIONAL */
	carma_j2735_MinuteOfTheYear_t	*minute;	/* OPTIONAL */
	carma_j2735_DSecond_t	*second;	/* OPTIONAL */
	carma_j2735_DSecond_t	*duration;	/* OPTIONAL */
	carma_j2735_PrioritizationResponseStatus_t	 status;
	struct carma_j2735_SignalStatusPackage__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_SignalStatusPackage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_SignalStatusPackage;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_SignalStatusPackage_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_SignalStatusPackage_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_SignalRequesterInfo.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_IntersectionAccessPoint.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_SignalStatusPackage_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
