/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PositionConfidence_H_
#define	_carma_j2735_PositionConfidence_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_PositionConfidence {
	carma_j2735_PositionConfidence_unavailable	= 0,
	carma_j2735_PositionConfidence_a500m	= 1,
	carma_j2735_PositionConfidence_a200m	= 2,
	carma_j2735_PositionConfidence_a100m	= 3,
	carma_j2735_PositionConfidence_a50m	= 4,
	carma_j2735_PositionConfidence_a20m	= 5,
	carma_j2735_PositionConfidence_a10m	= 6,
	carma_j2735_PositionConfidence_a5m	= 7,
	carma_j2735_PositionConfidence_a2m	= 8,
	carma_j2735_PositionConfidence_a1m	= 9,
	carma_j2735_PositionConfidence_a50cm	= 10,
	carma_j2735_PositionConfidence_a20cm	= 11,
	carma_j2735_PositionConfidence_a10cm	= 12,
	carma_j2735_PositionConfidence_a5cm	= 13,
	carma_j2735_PositionConfidence_a2cm	= 14,
	carma_j2735_PositionConfidence_a1cm	= 15
} e_carma_j2735_PositionConfidence;

/* carma_j2735_PositionConfidence */
typedef long	 carma_j2735_PositionConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_PositionConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_PositionConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_PositionConfidence_specs_1;
asn_struct_free_f carma_j2735_PositionConfidence_free;
asn_struct_print_f carma_j2735_PositionConfidence_print;
asn_constr_check_f carma_j2735_PositionConfidence_constraint;
per_type_decoder_f carma_j2735_PositionConfidence_decode_uper;
per_type_encoder_f carma_j2735_PositionConfidence_encode_uper;
per_type_decoder_f carma_j2735_PositionConfidence_decode_aper;
per_type_encoder_f carma_j2735_PositionConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_PositionConfidence_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
