/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestMessage01"
 * 	found in "/input/TestMessage01.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_MobilityHeader_H_
#define	_carma_j2735_MobilityHeader_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityStaticID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityDynamicID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityGUID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityTimestamp.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_MobilityHeader */
typedef struct carma_j2735_MobilityHeader {
	carma_j2735_MobilityStaticID_t	 hostStaticId;
	carma_j2735_MobilityStaticID_t	 targetStaticId;
	carma_j2735_MobilityDynamicID_t	 hostBSMId;
	carma_j2735_MobilityGUID_t	 planId;
	carma_j2735_MobilityTimestamp_t	 timestamp;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_MobilityHeader_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_MobilityHeader;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_MobilityHeader_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_MobilityHeader_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_MobilityHeader_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
