/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VehicleStatus_H_
#define	_carma_j2735_VehicleStatus_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_ExteriorLights.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LightbarInUse.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_BrakeAppliedPressure.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_CoefficientOfFriction.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SunSensor.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RainSensor.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AmbientAirTemperature.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AmbientAirPressure.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ThrottlePosition.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpeedConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_GNSSstatus.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringWheelAngle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringWheelAngleConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringWheelAngleRateOfChange.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DrivingWheelAngle.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_VerticalAccelerationThreshold.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_YawRateConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AccelerationConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ObstacleDistance.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_Angle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DDateTime.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleHeight.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_BumperHeights.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleMass.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TrailerWeight.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EssPrecipYesNo.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EssPrecipRate.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EssPrecipSituation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EssSolarRadiation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EssMobileFriction.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_WiperSet;
struct carma_j2735_BrakeSystemStatus;
struct carma_j2735_FullPositionVector;
struct carma_j2735_SpeedandHeadingandThrottleConfidence;
struct carma_j2735_VehicleIdent;
struct carma_j2735_J1939data;
struct carma_j2735_AccelerationSet4Way;
struct carma_j2735_ConfidenceSet;

/* carma_j2735_VehicleStatus */
typedef struct carma_j2735_VehicleStatus {
	carma_j2735_ExteriorLights_t	*lights;	/* OPTIONAL */
	carma_j2735_LightbarInUse_t	*lightBar;	/* OPTIONAL */
	struct carma_j2735_WiperSet	*wipers;	/* OPTIONAL */
	struct carma_j2735_BrakeSystemStatus	*brakeStatus;	/* OPTIONAL */
	carma_j2735_BrakeAppliedPressure_t	*brakePressure;	/* OPTIONAL */
	carma_j2735_CoefficientOfFriction_t	*roadFriction;	/* OPTIONAL */
	carma_j2735_SunSensor_t	*sunData;	/* OPTIONAL */
	carma_j2735_RainSensor_t	*rainData;	/* OPTIONAL */
	carma_j2735_AmbientAirTemperature_t	*airTemp;	/* OPTIONAL */
	carma_j2735_AmbientAirPressure_t	*airPres;	/* OPTIONAL */
	struct carma_j2735_VehicleStatus__steering {
		carma_j2735_SteeringWheelAngle_t	 angle;
		carma_j2735_SteeringWheelAngleConfidence_t	*confidence;	/* OPTIONAL */
		carma_j2735_SteeringWheelAngleRateOfChange_t	*rate;	/* OPTIONAL */
		carma_j2735_DrivingWheelAngle_t	*wheels;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *steering;
	struct carma_j2735_VehicleStatus__accelSets {
		struct carma_j2735_AccelerationSet4Way	*accel4way;	/* OPTIONAL */
		carma_j2735_VerticalAccelerationThreshold_t	*vertAccelThres;	/* OPTIONAL */
		carma_j2735_YawRateConfidence_t	*yawRateCon;	/* OPTIONAL */
		carma_j2735_AccelerationConfidence_t	*hozAccelCon;	/* OPTIONAL */
		struct carma_j2735_ConfidenceSet	*confidenceSet;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *accelSets;
	struct carma_j2735_VehicleStatus__object {
		carma_j2735_ObstacleDistance_t	 obDist;
		carma_j2735_DSRC_Angle_t	 obDirect;
		carma_j2735_DDateTime_t	 dateTime;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *object;
	struct carma_j2735_FullPositionVector	*fullPos;	/* OPTIONAL */
	carma_j2735_ThrottlePosition_t	*throttlePos;	/* OPTIONAL */
	struct carma_j2735_SpeedandHeadingandThrottleConfidence	*speedHeadC;	/* OPTIONAL */
	carma_j2735_SpeedConfidence_t	*speedC;	/* OPTIONAL */
	struct carma_j2735_VehicleStatus__vehicleData {
		carma_j2735_VehicleHeight_t	 height;
		carma_j2735_BumperHeights_t	 bumpers;
		carma_j2735_VehicleMass_t	 mass;
		carma_j2735_TrailerWeight_t	 trailerWeight;
		carma_j2735_VehicleType_t	 type;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleData;
	struct carma_j2735_VehicleIdent	*vehicleIdent;	/* OPTIONAL */
	struct carma_j2735_J1939data	*j1939data;	/* OPTIONAL */
	struct carma_j2735_VehicleStatus__weatherReport {
		carma_j2735_EssPrecipYesNo_t	 isRaining;
		carma_j2735_EssPrecipRate_t	*rainRate;	/* OPTIONAL */
		carma_j2735_EssPrecipSituation_t	*precipSituation;	/* OPTIONAL */
		carma_j2735_EssSolarRadiation_t	*solarRadiation;	/* OPTIONAL */
		carma_j2735_EssMobileFriction_t	*friction;	/* OPTIONAL */
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *weatherReport;
	carma_j2735_GNSSstatus_t	*gnssStatus;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_VehicleStatus_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VehicleStatus;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_VehicleStatus_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_VehicleStatus_1[22];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_WiperSet.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_BrakeSystemStatus.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_FullPositionVector.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpeedandHeadingandThrottleConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleIdent.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_J1939data.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AccelerationSet4Way.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ConfidenceSet.h"

#endif	/* _carma_j2735_VehicleStatus_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
