/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PersonalDeviceUsageState_H_
#define	_carma_j2735_PersonalDeviceUsageState_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_PersonalDeviceUsageState {
	carma_j2735_PersonalDeviceUsageState_unavailable	= 0,
	carma_j2735_PersonalDeviceUsageState_other	= 1,
	carma_j2735_PersonalDeviceUsageState_idle	= 2,
	carma_j2735_PersonalDeviceUsageState_listeningToAudio	= 3,
	carma_j2735_PersonalDeviceUsageState_typing	= 4,
	carma_j2735_PersonalDeviceUsageState_calling	= 5,
	carma_j2735_PersonalDeviceUsageState_playingGames	= 6,
	carma_j2735_PersonalDeviceUsageState_reading	= 7,
	carma_j2735_PersonalDeviceUsageState_viewing	= 8
} e_carma_j2735_PersonalDeviceUsageState;

/* carma_j2735_PersonalDeviceUsageState */
typedef BIT_STRING_t	 carma_j2735_PersonalDeviceUsageState_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_PersonalDeviceUsageState_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_PersonalDeviceUsageState;
asn_struct_free_f carma_j2735_PersonalDeviceUsageState_free;
asn_struct_print_f carma_j2735_PersonalDeviceUsageState_print;
asn_constr_check_f carma_j2735_PersonalDeviceUsageState_constraint;
per_type_decoder_f carma_j2735_PersonalDeviceUsageState_decode_uper;
per_type_encoder_f carma_j2735_PersonalDeviceUsageState_encode_uper;
per_type_decoder_f carma_j2735_PersonalDeviceUsageState_decode_aper;
per_type_encoder_f carma_j2735_PersonalDeviceUsageState_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_PersonalDeviceUsageState_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
