/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_Snapshot_H_
#define	_carma_j2735_Snapshot_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_FullPositionVector.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_VehicleSafetyExtensions;
struct carma_j2735_VehicleStatus;

/* carma_j2735_Snapshot */
typedef struct carma_j2735_Snapshot {
	carma_j2735_FullPositionVector_t	 thePosition;
	struct carma_j2735_VehicleSafetyExtensions	*safetyExt;	/* OPTIONAL */
	struct carma_j2735_VehicleStatus	*dataSet;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_Snapshot_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_Snapshot;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_Snapshot_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_Snapshot_1[3];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleSafetyExtensions.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleStatus.h"

#endif	/* _carma_j2735_Snapshot_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
