/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "TestMessage01"
 * 	found in "/input/TestMessage01.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_MobilityResponseFlag_H_
#define	_carma_j2735_MobilityResponseFlag_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/BOOLEAN.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_MobilityResponseFlag */
typedef BOOLEAN_t	 carma_j2735_MobilityResponseFlag_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_MobilityResponseFlag;
asn_struct_free_f carma_j2735_MobilityResponseFlag_free;
asn_struct_print_f carma_j2735_MobilityResponseFlag_print;
asn_constr_check_f carma_j2735_MobilityResponseFlag_constraint;
per_type_decoder_f carma_j2735_MobilityResponseFlag_decode_uper;
per_type_encoder_f carma_j2735_MobilityResponseFlag_encode_uper;
per_type_decoder_f carma_j2735_MobilityResponseFlag_decode_aper;
per_type_encoder_f carma_j2735_MobilityResponseFlag_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_MobilityResponseFlag_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
