/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_EmergencyVehicleAlert_H_
#define	_carma_j2735_EmergencyVehicleAlert_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_MinuteOfTheYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TemporaryID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RoadSideAlert.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ResponseType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleMass.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleGroupAffected.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_IncidentResponseEquipment.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ResponderGroupAffected.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_EmergencyDetails;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_EmergencyVehicleAlert */
typedef struct carma_j2735_EmergencyVehicleAlert {
	carma_j2735_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	carma_j2735_TemporaryID_t	*id;	/* OPTIONAL */
	carma_j2735_RoadSideAlert_t	 rsaMsg;
	carma_j2735_ResponseType_t	*responseType;	/* OPTIONAL */
	struct carma_j2735_EmergencyDetails	*details;	/* OPTIONAL */
	carma_j2735_VehicleMass_t	*mass;	/* OPTIONAL */
	carma_j2735_VehicleType_t	*basicType;	/* OPTIONAL */
	carma_j2735_VehicleGroupAffected_t	*vehicleType;	/* OPTIONAL */
	carma_j2735_IncidentResponseEquipment_t	*responseEquip;	/* OPTIONAL */
	carma_j2735_ResponderGroupAffected_t	*responderType;	/* OPTIONAL */
	struct carma_j2735_EmergencyVehicleAlert__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_EmergencyVehicleAlert_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_EmergencyVehicleAlert;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_EmergencyVehicleAlert_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_EmergencyVehicleAlert_1[11];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_EmergencyDetails.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_EmergencyVehicleAlert_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
