/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_LaneDataAttribute_H_
#define	_carma_j2735_LaneDataAttribute_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DeltaAngle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RoadwayCrownAngle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MergeDivergeNodeAngle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpeedLimitList.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_LaneDataAttribute_PR {
	carma_j2735_LaneDataAttribute_PR_NOTHING,	/* No components present */
	carma_j2735_LaneDataAttribute_PR_pathEndPointAngle,
	carma_j2735_LaneDataAttribute_PR_laneCrownPointCenter,
	carma_j2735_LaneDataAttribute_PR_laneCrownPointLeft,
	carma_j2735_LaneDataAttribute_PR_laneCrownPointRight,
	carma_j2735_LaneDataAttribute_PR_laneAngle,
	carma_j2735_LaneDataAttribute_PR_speedLimits,
	carma_j2735_LaneDataAttribute_PR_regional
	/* Extensions may appear below */
	
} carma_j2735_LaneDataAttribute_PR;

/* Forward declarations */
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_LaneDataAttribute */
typedef struct carma_j2735_LaneDataAttribute {
	carma_j2735_LaneDataAttribute_PR present;
	union carma_j2735_LaneDataAttribute_u {
		carma_j2735_DeltaAngle_t	 pathEndPointAngle;
		carma_j2735_RoadwayCrownAngle_t	 laneCrownPointCenter;
		carma_j2735_RoadwayCrownAngle_t	 laneCrownPointLeft;
		carma_j2735_RoadwayCrownAngle_t	 laneCrownPointRight;
		carma_j2735_MergeDivergeNodeAngle_t	 laneAngle;
		carma_j2735_SpeedLimitList_t	 speedLimits;
		struct carma_j2735_LaneDataAttribute__regional {
			A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} regional;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_LaneDataAttribute_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_LaneDataAttribute;
extern asn_CHOICE_specifics_t asn_SPC_carma_j2735_LaneDataAttribute_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_LaneDataAttribute_1[7];
extern asn_per_constraints_t asn_PER_type_carma_j2735_LaneDataAttribute_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_LaneDataAttribute_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
