/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_LaneTypeAttributes_H_
#define	_carma_j2735_LaneTypeAttributes_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Vehicle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Crosswalk.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Bike.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Sidewalk.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Barrier.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Striping.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-TrackedVehicle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneAttributes-Parking.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_LaneTypeAttributes_PR {
	carma_j2735_LaneTypeAttributes_PR_NOTHING,	/* No components present */
	carma_j2735_LaneTypeAttributes_PR_vehicle,
	carma_j2735_LaneTypeAttributes_PR_crosswalk,
	carma_j2735_LaneTypeAttributes_PR_bikeLane,
	carma_j2735_LaneTypeAttributes_PR_sidewalk,
	carma_j2735_LaneTypeAttributes_PR_median,
	carma_j2735_LaneTypeAttributes_PR_striping,
	carma_j2735_LaneTypeAttributes_PR_trackedVehicle,
	carma_j2735_LaneTypeAttributes_PR_parking
	/* Extensions may appear below */
	
} carma_j2735_LaneTypeAttributes_PR;

/* carma_j2735_LaneTypeAttributes */
typedef struct carma_j2735_LaneTypeAttributes {
	carma_j2735_LaneTypeAttributes_PR present;
	union carma_j2735_LaneTypeAttributes_u {
		carma_j2735_LaneAttributes_Vehicle_t	 vehicle;
		carma_j2735_LaneAttributes_Crosswalk_t	 crosswalk;
		carma_j2735_LaneAttributes_Bike_t	 bikeLane;
		carma_j2735_LaneAttributes_Sidewalk_t	 sidewalk;
		carma_j2735_LaneAttributes_Barrier_t	 median;
		carma_j2735_LaneAttributes_Striping_t	 striping;
		carma_j2735_LaneAttributes_TrackedVehicle_t	 trackedVehicle;
		carma_j2735_LaneAttributes_Parking_t	 parking;
		/*
		 * This type is extensible,
		 * possible extensions are below.
		 */
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_LaneTypeAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_LaneTypeAttributes;
extern asn_CHOICE_specifics_t asn_SPC_carma_j2735_LaneTypeAttributes_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_LaneTypeAttributes_1[8];
extern asn_per_constraints_t asn_PER_type_carma_j2735_LaneTypeAttributes_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_LaneTypeAttributes_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
