/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_J1939data_H_
#define	_carma_j2735_J1939data_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_TrailerWeight.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_CargoWeight.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringAxleTemperature.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DriveAxleLocation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DriveAxleLiftAirPressure.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DriveAxleTemperature.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DriveAxleLubePressure.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringAxleLubePressure.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_TireDataList;
struct carma_j2735_AxleWeightList;

/* carma_j2735_J1939data */
typedef struct carma_j2735_J1939data {
	struct carma_j2735_TireDataList	*tires;	/* OPTIONAL */
	struct carma_j2735_AxleWeightList	*axles;	/* OPTIONAL */
	carma_j2735_TrailerWeight_t	*trailerWeight;	/* OPTIONAL */
	carma_j2735_CargoWeight_t	*cargoWeight;	/* OPTIONAL */
	carma_j2735_SteeringAxleTemperature_t	*steeringAxleTemperature;	/* OPTIONAL */
	carma_j2735_DriveAxleLocation_t	*driveAxleLocation;	/* OPTIONAL */
	carma_j2735_DriveAxleLiftAirPressure_t	*driveAxleLiftAirPressure;	/* OPTIONAL */
	carma_j2735_DriveAxleTemperature_t	*driveAxleTemperature;	/* OPTIONAL */
	carma_j2735_DriveAxleLubePressure_t	*driveAxleLubePressure;	/* OPTIONAL */
	carma_j2735_SteeringAxleLubePressure_t	*steeringAxleLubePressure;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_J1939data_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_J1939data;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_J1939data_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_J1939data_1[10];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_TireDataList.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AxleWeightList.h"

#endif	/* _carma_j2735_J1939data_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
