/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_RequestedItem_H_
#define	_carma_j2735_RequestedItem_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_RequestedItem {
	carma_j2735_RequestedItem_reserved	= 0,
	carma_j2735_RequestedItem_itemA	= 1,
	carma_j2735_RequestedItem_itemB	= 2,
	carma_j2735_RequestedItem_itemC	= 3,
	carma_j2735_RequestedItem_itemD	= 4,
	carma_j2735_RequestedItem_itemE	= 5,
	carma_j2735_RequestedItem_itemF	= 6,
	carma_j2735_RequestedItem_itemG	= 7,
	carma_j2735_RequestedItem_itemI	= 8,
	carma_j2735_RequestedItem_itemJ	= 9,
	carma_j2735_RequestedItem_itemK	= 10,
	carma_j2735_RequestedItem_itemL	= 11,
	carma_j2735_RequestedItem_itemM	= 12,
	carma_j2735_RequestedItem_itemN	= 13,
	carma_j2735_RequestedItem_itemO	= 14,
	carma_j2735_RequestedItem_itemP	= 15,
	carma_j2735_RequestedItem_itemQ	= 16
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_RequestedItem;

/* carma_j2735_RequestedItem */
typedef long	 carma_j2735_RequestedItem_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_RequestedItem_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_RequestedItem;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_RequestedItem_specs_1;
asn_struct_free_f carma_j2735_RequestedItem_free;
asn_struct_print_f carma_j2735_RequestedItem_print;
asn_constr_check_f carma_j2735_RequestedItem_constraint;
per_type_decoder_f carma_j2735_RequestedItem_decode_uper;
per_type_encoder_f carma_j2735_RequestedItem_encode_uper;
per_type_decoder_f carma_j2735_RequestedItem_decode_aper;
per_type_encoder_f carma_j2735_RequestedItem_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_RequestedItem_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
