/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_TrailerHistoryPoint_H_
#define	_carma_j2735_TrailerHistoryPoint_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_Angle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TimeOffset.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-24b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B07.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_CoarseHeading.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_TrailerHistoryPoint */
typedef struct carma_j2735_TrailerHistoryPoint {
	carma_j2735_DSRC_Angle_t	 pivotAngle;
	carma_j2735_TimeOffset_t	 timeOffset;
	carma_j2735_Node_XY_24b_t	 positionOffset;
	carma_j2735_VertOffset_B07_t	*elevationOffset;	/* OPTIONAL */
	carma_j2735_CoarseHeading_t	*heading;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_TrailerHistoryPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_TrailerHistoryPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_TrailerHistoryPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_TrailerHistoryPoint_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_TrailerHistoryPoint_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
