/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PathHistoryPoint_H_
#define	_carma_j2735_PathHistoryPoint_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_OffsetLL-B18.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B12.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TimeOffset.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Speed.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_CoarseHeading.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_PositionalAccuracy;

/* carma_j2735_PathHistoryPoint */
typedef struct carma_j2735_PathHistoryPoint {
	carma_j2735_OffsetLL_B18_t	 latOffset;
	carma_j2735_OffsetLL_B18_t	 lonOffset;
	carma_j2735_VertOffset_B12_t	 elevationOffset;
	carma_j2735_TimeOffset_t	 timeOffset;
	carma_j2735_Speed_t	*speed;	/* OPTIONAL */
	struct carma_j2735_PositionalAccuracy	*posAccuracy;	/* OPTIONAL */
	carma_j2735_CoarseHeading_t	*heading;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_PathHistoryPoint_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_PathHistoryPoint;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_PathHistoryPoint_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_PathHistoryPoint_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_PositionalAccuracy.h"

#endif	/* _carma_j2735_PathHistoryPoint_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
