/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_RequestorType_H_
#define	_carma_j2735_RequestorType_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_BasicVehicleRole.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RequestSubRole.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RequestImportanceLevel.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Iso3833VehicleType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleType.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_RequestorType */
typedef struct carma_j2735_RequestorType {
	carma_j2735_BasicVehicleRole_t	 role;
	carma_j2735_RequestSubRole_t	*subrole;	/* OPTIONAL */
	carma_j2735_RequestImportanceLevel_t	*request;	/* OPTIONAL */
	carma_j2735_Iso3833VehicleType_t	*iso3883;	/* OPTIONAL */
	carma_j2735_VehicleType_t	*hpmsType;	/* OPTIONAL */
	struct carma_j2735_Reg_BasicSafetyMessage	*regional;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_RequestorType_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_RequestorType;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_RequestorType_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_RequestorType_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_RequestorType_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
