/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_RegionalExtension_H_
#define	_carma_j2735_RegionalExtension_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionId.h"
#include <etsi_its_carma_j2735_coding/ANY.h>
#include <etsi_its_carma_j2735_coding/asn_ioc.h>
#include <etsi_its_carma_j2735_coding/OPEN_TYPE.h>
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_Reg_BasicSafetyMessage__regExtValue_PR {
	carma_j2735_Reg_BasicSafetyMessage__regExtValue_PR_NOTHING	/* No components present */
	
} carma_j2735_Reg_BasicSafetyMessage__regExtValue_PR;

/* carma_j2735_RegionalExtension */
typedef struct carma_j2735_Reg_BasicSafetyMessage {
	carma_j2735_RegionId_t	 regionId;
	struct carma_j2735_Reg_BasicSafetyMessage__regExtValue {
		carma_j2735_Reg_BasicSafetyMessage__regExtValue_PR present;
		union carma_j2735_Reg_BasicSafetyMessage__carma_j2735_regExtValue_u {
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} regExtValue;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_Reg_BasicSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_Reg_BasicSafetyMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_Reg_BasicSafetyMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_Reg_BasicSafetyMessage_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_RegionalExtension_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
