/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_MobilityRequest_H_
#define	_carma_j2735_MobilityRequest_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityStrategy.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityPlanType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityUrgency.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityLocation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityParameters.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityTimestamp.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_MobilityLocation;
struct carma_j2735_MobilityLocationOffsets;

/* carma_j2735_MobilityRequest */
typedef struct carma_j2735_MobilityRequest {
	carma_j2735_MobilityStrategy_t	 strategy;
	carma_j2735_MobilityPlanType_t	 planType;
	carma_j2735_MobilityUrgency_t	 urgency;
	carma_j2735_MobilityLocation_t	 location;
	carma_j2735_MobilityParameters_t	 strategyParams;
	struct carma_j2735_MobilityLocation	*trajectoryStart;	/* OPTIONAL */
	struct carma_j2735_MobilityLocationOffsets	*trajectory;	/* OPTIONAL */
	carma_j2735_MobilityTimestamp_t	*expiration;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_MobilityRequest_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_MobilityRequest;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_MobilityRequest_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_MobilityRequest_1[8];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityLocation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MobilityLocationOffsets.h"

#endif	/* _carma_j2735_MobilityRequest_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
