/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _carma_j2735_ASN_CONSTANT_H
#define _carma_j2735_ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_carma_j2735_MobilityUrgency (0)
#define max_val_carma_j2735_MobilityUrgency (1000)


#ifdef __cplusplus
}
#endif

#endif /* _carma_j2735_ASN_CONSTANT_H */
