/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_DisabledVehicle_H_
#define	_carma_j2735_DisabledVehicle_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_ITIScodes.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_GenericLocations.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_DisabledVehicle */
typedef struct carma_j2735_DisabledVehicle {
	carma_j2735_ITIScodes_t	 statusDetails;
	carma_j2735_GenericLocations_t	*locationDetails;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_DisabledVehicle_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_DisabledVehicle;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_DisabledVehicle_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_DisabledVehicle_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_DisabledVehicle_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
