/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_TrailerUnitDescription_H_
#define	_carma_j2735_TrailerUnitDescription_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_IsDolly.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleWidth.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleLength.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleHeight.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TrailerMass.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PivotPointDescription.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Offset-B12.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-24b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B07.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_BumperHeights;
struct carma_j2735_PivotPointDescription;
struct carma_j2735_TrailerHistoryPointList;

/* carma_j2735_TrailerUnitDescription */
typedef struct carma_j2735_TrailerUnitDescription {
	carma_j2735_IsDolly_t	 isDolly;
	carma_j2735_VehicleWidth_t	 width;
	carma_j2735_VehicleLength_t	 length;
	carma_j2735_VehicleHeight_t	*height;	/* OPTIONAL */
	carma_j2735_TrailerMass_t	*mass;	/* OPTIONAL */
	struct carma_j2735_BumperHeights	*bumperHeights;	/* OPTIONAL */
	carma_j2735_VehicleHeight_t	*centerOfGravity;	/* OPTIONAL */
	carma_j2735_PivotPointDescription_t	 frontPivot;
	struct carma_j2735_PivotPointDescription	*rearPivot;	/* OPTIONAL */
	carma_j2735_Offset_B12_t	*rearWheelOffset;	/* OPTIONAL */
	carma_j2735_Node_XY_24b_t	 positionOffset;
	carma_j2735_VertOffset_B07_t	*elevationOffset;	/* OPTIONAL */
	struct carma_j2735_TrailerHistoryPointList	*crumbData;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_TrailerUnitDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_TrailerUnitDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_TrailerUnitDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_TrailerUnitDescription_1[13];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_BumperHeights.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PivotPointDescription.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TrailerHistoryPointList.h"

#endif	/* _carma_j2735_TrailerUnitDescription_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
