/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VerticalOffset_H_
#define	_carma_j2735_VerticalOffset_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B07.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B08.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B09.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B10.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B11.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VertOffset-B12.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_Elevation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_VerticalOffset_PR {
	carma_j2735_VerticalOffset_PR_NOTHING,	/* No components present */
	carma_j2735_VerticalOffset_PR_offset1,
	carma_j2735_VerticalOffset_PR_offset2,
	carma_j2735_VerticalOffset_PR_offset3,
	carma_j2735_VerticalOffset_PR_offset4,
	carma_j2735_VerticalOffset_PR_offset5,
	carma_j2735_VerticalOffset_PR_offset6,
	carma_j2735_VerticalOffset_PR_elevation,
	carma_j2735_VerticalOffset_PR_regional
} carma_j2735_VerticalOffset_PR;

/* carma_j2735_VerticalOffset */
typedef struct carma_j2735_VerticalOffset {
	carma_j2735_VerticalOffset_PR present;
	union carma_j2735_VerticalOffset_u {
		carma_j2735_VertOffset_B07_t	 offset1;
		carma_j2735_VertOffset_B08_t	 offset2;
		carma_j2735_VertOffset_B09_t	 offset3;
		carma_j2735_VertOffset_B10_t	 offset4;
		carma_j2735_VertOffset_B11_t	 offset5;
		carma_j2735_VertOffset_B12_t	 offset6;
		carma_j2735_DSRC_Elevation_t	 elevation;
		carma_j2735_Reg_BasicSafetyMessage_t	 regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_VerticalOffset_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VerticalOffset;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_VerticalOffset_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
