/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ConnectsToList_H_
#define	_carma_j2735_ConnectsToList_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_Connection;

/* carma_j2735_ConnectsToList */
typedef struct carma_j2735_ConnectsToList {
	A_SEQUENCE_OF(struct carma_j2735_Connection) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ConnectsToList_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ConnectsToList;
extern asn_SET_OF_specifics_t asn_SPC_carma_j2735_ConnectsToList_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ConnectsToList_1[1];
extern asn_per_constraints_t asn_PER_type_carma_j2735_ConnectsToList_constr_1;

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_Connection.h"

#endif	/* _carma_j2735_ConnectsToList_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
