/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ComputedLane_H_
#define	_carma_j2735_ComputedLane_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_Angle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Scale-B12.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DrivenLineOffsetSm.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DrivenLineOffsetLg.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ComputedLane__offsetXaxis_PR {
	carma_j2735_ComputedLane__offsetXaxis_PR_NOTHING,	/* No components present */
	carma_j2735_ComputedLane__offsetXaxis_PR_small,
	carma_j2735_ComputedLane__offsetXaxis_PR_large
} carma_j2735_ComputedLane__offsetXaxis_PR;
typedef enum carma_j2735_ComputedLane__offsetYaxis_PR {
	carma_j2735_ComputedLane__offsetYaxis_PR_NOTHING,	/* No components present */
	carma_j2735_ComputedLane__offsetYaxis_PR_small,
	carma_j2735_ComputedLane__offsetYaxis_PR_large
} carma_j2735_ComputedLane__offsetYaxis_PR;

/* Forward declarations */
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_ComputedLane */
typedef struct carma_j2735_ComputedLane {
	carma_j2735_LaneID_t	 referenceLaneId;
	struct carma_j2735_ComputedLane__offsetXaxis {
		carma_j2735_ComputedLane__offsetXaxis_PR present;
		union carma_j2735_ComputedLane__carma_j2735_offsetXaxis_u {
			carma_j2735_DrivenLineOffsetSm_t	 small;
			carma_j2735_DrivenLineOffsetLg_t	 large;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offsetXaxis;
	struct carma_j2735_ComputedLane__offsetYaxis {
		carma_j2735_ComputedLane__offsetYaxis_PR present;
		union carma_j2735_ComputedLane__carma_j2735_offsetYaxis_u {
			carma_j2735_DrivenLineOffsetSm_t	 small;
			carma_j2735_DrivenLineOffsetLg_t	 large;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} offsetYaxis;
	carma_j2735_DSRC_Angle_t	*rotateXY;	/* OPTIONAL */
	carma_j2735_Scale_B12_t	*scaleXaxis;	/* OPTIONAL */
	carma_j2735_Scale_B12_t	*scaleYaxis;	/* OPTIONAL */
	struct carma_j2735_ComputedLane__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ComputedLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ComputedLane;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_ComputedLane_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ComputedLane_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_ComputedLane_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
