/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_NodeAttributeSetLL_H_
#define	_carma_j2735_NodeAttributeSetLL_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_Offset-B10.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_NodeAttributeLLList;
struct carma_j2735_SegmentAttributeLLList;
struct carma_j2735_LaneDataAttributeList;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_NodeAttributeSetLL */
typedef struct carma_j2735_NodeAttributeSetLL {
	struct carma_j2735_NodeAttributeLLList	*localNode;	/* OPTIONAL */
	struct carma_j2735_SegmentAttributeLLList	*disabled;	/* OPTIONAL */
	struct carma_j2735_SegmentAttributeLLList	*enabled;	/* OPTIONAL */
	struct carma_j2735_LaneDataAttributeList	*data;	/* OPTIONAL */
	carma_j2735_Offset_B10_t	*dWidth;	/* OPTIONAL */
	carma_j2735_Offset_B10_t	*dElevation;	/* OPTIONAL */
	struct carma_j2735_NodeAttributeSetLL__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_NodeAttributeSetLL_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_NodeAttributeSetLL;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_NodeAttributeSetLL_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_NodeAttributeSetLL_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_NodeAttributeLLList.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SegmentAttributeLLList.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneDataAttributeList.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_NodeAttributeSetLL_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
