/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_Location_tech_H_
#define	_carma_j2735_Location_tech_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_Location_tech {
	carma_j2735_Location_tech_loc_tech_unknown	= 0,
	carma_j2735_Location_tech_loc_tech_GNSS	= 1,
	carma_j2735_Location_tech_loc_tech_DGPS	= 2,
	carma_j2735_Location_tech_loc_tech_RTK	= 3,
	carma_j2735_Location_tech_loc_tech_PPP	= 4,
	carma_j2735_Location_tech_loc_tech_drGPS	= 5,
	carma_j2735_Location_tech_loc_tech_drDGPS	= 6,
	carma_j2735_Location_tech_loc_tech_dr	= 7,
	carma_j2735_Location_tech_loc_tech_nav	= 8,
	carma_j2735_Location_tech_loc_tech_fault	= 9
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_Location_tech;

/* carma_j2735_Location-tech */
typedef long	 carma_j2735_Location_tech_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_Location_tech;
asn_struct_free_f carma_j2735_Location_tech_free;
asn_struct_print_f carma_j2735_Location_tech_print;
asn_constr_check_f carma_j2735_Location_tech_constraint;
per_type_decoder_f carma_j2735_Location_tech_decode_uper;
per_type_encoder_f carma_j2735_Location_tech_encode_uper;
per_type_decoder_f carma_j2735_Location_tech_decode_aper;
per_type_encoder_f carma_j2735_Location_tech_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_Location_tech_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
