/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_RequestorDescription_H_
#define	_carma_j2735_RequestorDescription_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DescriptiveName.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TransitVehicleStatus.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TransitVehicleOccupancy.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DeltaTime.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_RequestorType;
struct carma_j2735_RequestorPositionVector;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_RequestorDescription */
typedef struct carma_j2735_RequestorDescription {
	carma_j2735_VehicleID_t	 id;
	struct carma_j2735_RequestorType	*type;	/* OPTIONAL */
	struct carma_j2735_RequestorPositionVector	*position;	/* OPTIONAL */
	carma_j2735_DescriptiveName_t	*name;	/* OPTIONAL */
	carma_j2735_DescriptiveName_t	*routeName;	/* OPTIONAL */
	carma_j2735_TransitVehicleStatus_t	*transitStatus;	/* OPTIONAL */
	carma_j2735_TransitVehicleOccupancy_t	*transitOccupancy;	/* OPTIONAL */
	carma_j2735_DeltaTime_t	*transitSchedule;	/* OPTIONAL */
	struct carma_j2735_RequestorDescription__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_RequestorDescription_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_RequestorDescription;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_RequestorDescription_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_RequestorDescription_1[9];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RequestorType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RequestorPositionVector.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_RequestorDescription_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
