/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_GenericLocations_H_
#define	_carma_j2735_GenericLocations_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_GenericLocations {
	carma_j2735_GenericLocations_on_bridges	= 7937,
	carma_j2735_GenericLocations_in_tunnels	= 7938,
	carma_j2735_GenericLocations_entering_or_leaving_tunnels	= 7939,
	carma_j2735_GenericLocations_on_ramps	= 7940,
	carma_j2735_GenericLocations_in_road_construction_area	= 7941,
	carma_j2735_GenericLocations_around_a_curve	= 7942,
	carma_j2735_GenericLocations_on_curve	= 8026,
	carma_j2735_GenericLocations_on_tracks	= 8009,
	carma_j2735_GenericLocations_in_street	= 8025,
	carma_j2735_GenericLocations_shoulder	= 8027,
	carma_j2735_GenericLocations_on_minor_roads	= 7943,
	carma_j2735_GenericLocations_in_the_opposing_lanes	= 7944,
	carma_j2735_GenericLocations_adjacent_to_roadway	= 7945,
	carma_j2735_GenericLocations_across_tracks	= 8024,
	carma_j2735_GenericLocations_on_bend	= 7946,
	carma_j2735_GenericLocations_intersection	= 8032,
	carma_j2735_GenericLocations_entire_intersection	= 7947,
	carma_j2735_GenericLocations_in_the_median	= 7948,
	carma_j2735_GenericLocations_moved_to_side_of_road	= 7949,
	carma_j2735_GenericLocations_moved_to_shoulder	= 7950,
	carma_j2735_GenericLocations_on_the_roadway	= 7951,
	carma_j2735_GenericLocations_dip	= 8010,
	carma_j2735_GenericLocations_traffic_circle	= 8011,
	carma_j2735_GenericLocations_crossover	= 8028,
	carma_j2735_GenericLocations_cross_road	= 8029,
	carma_j2735_GenericLocations_side_road	= 8030,
	carma_j2735_GenericLocations_to	= 8014,
	carma_j2735_GenericLocations_by	= 8015,
	carma_j2735_GenericLocations_through	= 8016,
	carma_j2735_GenericLocations_area_of	= 8017,
	carma_j2735_GenericLocations_under	= 8018,
	carma_j2735_GenericLocations_over	= 8019,
	carma_j2735_GenericLocations_from	= 8020,
	carma_j2735_GenericLocations_approaching	= 8021,
	carma_j2735_GenericLocations_entering_at	= 8022,
	carma_j2735_GenericLocations_exiting_at	= 8023,
	carma_j2735_GenericLocations_in_shaded_areas	= 7952,
	carma_j2735_GenericLocations_in_low_lying_areas	= 7953,
	carma_j2735_GenericLocations_in_the_downtown_area	= 7954,
	carma_j2735_GenericLocations_in_the_inner_city_area	= 7955,
	carma_j2735_GenericLocations_in_parts	= 7956,
	carma_j2735_GenericLocations_in_some_places	= 7957,
	carma_j2735_GenericLocations_in_the_ditch	= 7958,
	carma_j2735_GenericLocations_in_the_valley	= 7959,
	carma_j2735_GenericLocations_on_hill_top	= 7960,
	carma_j2735_GenericLocations_near_the_foothills	= 7961,
	carma_j2735_GenericLocations_at_high_altitudes	= 7962,
	carma_j2735_GenericLocations_near_the_lake	= 7963,
	carma_j2735_GenericLocations_near_the_shore	= 7964,
	carma_j2735_GenericLocations_nearby_basin	= 8008,
	carma_j2735_GenericLocations_over_the_crest_of_a_hill	= 7965,
	carma_j2735_GenericLocations_other_than_on_the_roadway	= 7966,
	carma_j2735_GenericLocations_near_the_beach	= 7967,
	carma_j2735_GenericLocations_near_beach_access_point	= 7968,
	carma_j2735_GenericLocations_mountain_pass	= 8006,
	carma_j2735_GenericLocations_lower_level	= 7969,
	carma_j2735_GenericLocations_upper_level	= 7970,
	carma_j2735_GenericLocations_airport	= 7971,
	carma_j2735_GenericLocations_concourse	= 7972,
	carma_j2735_GenericLocations_gate	= 7973,
	carma_j2735_GenericLocations_baggage_claim	= 7974,
	carma_j2735_GenericLocations_customs_point	= 7975,
	carma_j2735_GenericLocations_reservation_center	= 8007,
	carma_j2735_GenericLocations_station	= 7976,
	carma_j2735_GenericLocations_platform	= 7977,
	carma_j2735_GenericLocations_dock	= 7978,
	carma_j2735_GenericLocations_depot	= 7979,
	carma_j2735_GenericLocations_ev_charging_point	= 7980,
	carma_j2735_GenericLocations_information_welcome_point	= 7981,
	carma_j2735_GenericLocations_at_rest_area	= 7982,
	carma_j2735_GenericLocations_at_service_area	= 7983,
	carma_j2735_GenericLocations_at_weigh_station	= 7984,
	carma_j2735_GenericLocations_roadside_park	= 8033,
	carma_j2735_GenericLocations_picnic_areas	= 7985,
	carma_j2735_GenericLocations_rest_area	= 7986,
	carma_j2735_GenericLocations_service_stations	= 7987,
	carma_j2735_GenericLocations_toilets	= 7988,
	carma_j2735_GenericLocations_bus_stop	= 8031,
	carma_j2735_GenericLocations_park_and_ride_lot	= 8012,
	carma_j2735_GenericLocations_on_the_right	= 7989,
	carma_j2735_GenericLocations_on_the_left	= 7990,
	carma_j2735_GenericLocations_in_the_center	= 7991,
	carma_j2735_GenericLocations_in_the_opposite_direction	= 7992,
	carma_j2735_GenericLocations_cross_traffic	= 7993,
	carma_j2735_GenericLocations_northbound_traffic	= 7994,
	carma_j2735_GenericLocations_eastbound_traffic	= 7995,
	carma_j2735_GenericLocations_southbound_traffic	= 7996,
	carma_j2735_GenericLocations_westbound_traffic	= 7997,
	carma_j2735_GenericLocations_north	= 7998,
	carma_j2735_GenericLocations_south	= 7999,
	carma_j2735_GenericLocations_east	= 8000,
	carma_j2735_GenericLocations_west	= 8001,
	carma_j2735_GenericLocations_northeast	= 8002,
	carma_j2735_GenericLocations_northwest	= 8003,
	carma_j2735_GenericLocations_southeast	= 8004,
	carma_j2735_GenericLocations_southwest	= 8005
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_GenericLocations;

/* carma_j2735_GenericLocations */
typedef long	 carma_j2735_GenericLocations_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_GenericLocations_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_GenericLocations;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_GenericLocations_specs_1;
asn_struct_free_f carma_j2735_GenericLocations_free;
asn_struct_print_f carma_j2735_GenericLocations_print;
asn_constr_check_f carma_j2735_GenericLocations_constraint;
per_type_decoder_f carma_j2735_GenericLocations_decode_uper;
per_type_encoder_f carma_j2735_GenericLocations_encode_uper;
per_type_decoder_f carma_j2735_GenericLocations_decode_aper;
per_type_encoder_f carma_j2735_GenericLocations_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_GenericLocations_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
