/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_MessageFrame_H_
#define	_carma_j2735_MessageFrame_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRCmsgID.h"
#include <etsi_its_carma_j2735_coding/ANY.h>
#include <etsi_its_carma_j2735_coding/asn_ioc.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_BasicSafetyMessage.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MapData.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SPAT.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_CommonSafetyRequest.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_EmergencyVehicleAlert.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_IntersectionCollision.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_NMEAcorrections.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ProbeDataManagement.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ProbeVehicleData.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RoadSideAlert.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RTCMcorrections.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SignalRequestMessage.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SignalStatusMessage.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TravelerInformation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalSafetyMessage.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage00.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage01.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage02.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage03.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage04.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage05.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage06.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage07.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage08.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage09.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage10.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage11.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage12.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage13.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage14.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TestMessage15.h"
#include <etsi_its_carma_j2735_coding/OPEN_TYPE.h>
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_MessageFrame__value_PR {
	carma_j2735_MessageFrame__value_PR_NOTHING,	/* No components present */
	carma_j2735_MessageFrame__value_PR_BasicSafetyMessage,
	carma_j2735_MessageFrame__value_PR_MapData,
	carma_j2735_MessageFrame__value_PR_SPAT,
	carma_j2735_MessageFrame__value_PR_CommonSafetyRequest,
	carma_j2735_MessageFrame__value_PR_EmergencyVehicleAlert,
	carma_j2735_MessageFrame__value_PR_IntersectionCollision,
	carma_j2735_MessageFrame__value_PR_NMEAcorrections,
	carma_j2735_MessageFrame__value_PR_ProbeDataManagement,
	carma_j2735_MessageFrame__value_PR_ProbeVehicleData,
	carma_j2735_MessageFrame__value_PR_RoadSideAlert,
	carma_j2735_MessageFrame__value_PR_RTCMcorrections,
	carma_j2735_MessageFrame__value_PR_SignalRequestMessage,
	carma_j2735_MessageFrame__value_PR_SignalStatusMessage,
	carma_j2735_MessageFrame__value_PR_TravelerInformation,
	carma_j2735_MessageFrame__value_PR_PersonalSafetyMessage,
	carma_j2735_MessageFrame__value_PR_TestMessage00,
	carma_j2735_MessageFrame__value_PR_TestMessage01,
	carma_j2735_MessageFrame__value_PR_TestMessage02,
	carma_j2735_MessageFrame__value_PR_TestMessage03,
	carma_j2735_MessageFrame__value_PR_TestMessage04,
	carma_j2735_MessageFrame__value_PR_TestMessage05,
	carma_j2735_MessageFrame__value_PR_TestMessage06,
	carma_j2735_MessageFrame__value_PR_TestMessage07,
	carma_j2735_MessageFrame__value_PR_TestMessage08,
	carma_j2735_MessageFrame__value_PR_TestMessage09,
	carma_j2735_MessageFrame__value_PR_TestMessage10,
	carma_j2735_MessageFrame__value_PR_TestMessage11,
	carma_j2735_MessageFrame__value_PR_TestMessage12,
	carma_j2735_MessageFrame__value_PR_TestMessage13,
	carma_j2735_MessageFrame__value_PR_TestMessage14,
	carma_j2735_MessageFrame__value_PR_TestMessage15
} carma_j2735_MessageFrame__value_PR;

/* carma_j2735_MessageFrame */
typedef struct carma_j2735_MessageFrame {
	carma_j2735_DSRCmsgID_t	 messageId;
	struct carma_j2735_MessageFrame__value {
		carma_j2735_MessageFrame__value_PR present;
		union carma_j2735_MessageFrame__carma_j2735_value_u {
			carma_j2735_BasicSafetyMessage_t	 BasicSafetyMessage;
			carma_j2735_MapData_t	 MapData;
			carma_j2735_SPAT_t	 SPAT;
			carma_j2735_CommonSafetyRequest_t	 CommonSafetyRequest;
			carma_j2735_EmergencyVehicleAlert_t	 EmergencyVehicleAlert;
			carma_j2735_IntersectionCollision_t	 IntersectionCollision;
			carma_j2735_NMEAcorrections_t	 NMEAcorrections;
			carma_j2735_ProbeDataManagement_t	 ProbeDataManagement;
			carma_j2735_ProbeVehicleData_t	 ProbeVehicleData;
			carma_j2735_RoadSideAlert_t	 RoadSideAlert;
			carma_j2735_RTCMcorrections_t	 RTCMcorrections;
			carma_j2735_SignalRequestMessage_t	 SignalRequestMessage;
			carma_j2735_SignalStatusMessage_t	 SignalStatusMessage;
			carma_j2735_TravelerInformation_t	 TravelerInformation;
			carma_j2735_PersonalSafetyMessage_t	 PersonalSafetyMessage;
			carma_j2735_TestMessage00_t	 TestMessage00;
			carma_j2735_TestMessage01_t	 TestMessage01;
			carma_j2735_TestMessage02_t	 TestMessage02;
			carma_j2735_TestMessage03_t	 TestMessage03;
			carma_j2735_TestMessage04_t	 TestMessage04;
			carma_j2735_TestMessage05_t	 TestMessage05;
			carma_j2735_TestMessage06_t	 TestMessage06;
			carma_j2735_TestMessage07_t	 TestMessage07;
			carma_j2735_TestMessage08_t	 TestMessage08;
			carma_j2735_TestMessage09_t	 TestMessage09;
			carma_j2735_TestMessage10_t	 TestMessage10;
			carma_j2735_TestMessage11_t	 TestMessage11;
			carma_j2735_TestMessage12_t	 TestMessage12;
			carma_j2735_TestMessage13_t	 TestMessage13;
			carma_j2735_TestMessage14_t	 TestMessage14;
			carma_j2735_TestMessage15_t	 TestMessage15;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_MessageFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_MessageFrame;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_MessageFrame_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
