/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ProbeVehicleData_H_
#define	_carma_j2735_ProbeVehicleData_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_MinuteOfTheYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ProbeSegmentNumber.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_FullPositionVector.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleClassification.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_VehicleIdent;
struct carma_j2735_Snapshot;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_ProbeVehicleData */
typedef struct carma_j2735_ProbeVehicleData {
	carma_j2735_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	carma_j2735_ProbeSegmentNumber_t	*segNum;	/* OPTIONAL */
	struct carma_j2735_VehicleIdent	*probeID;	/* OPTIONAL */
	carma_j2735_FullPositionVector_t	 startVector;
	carma_j2735_VehicleClassification_t	 vehicleType;
	struct carma_j2735_ProbeVehicleData__snapshots {
		A_SEQUENCE_OF(struct carma_j2735_Snapshot) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} snapshots;
	struct carma_j2735_ProbeVehicleData__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ProbeVehicleData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ProbeVehicleData;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_ProbeVehicleData_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ProbeVehicleData_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleIdent.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Snapshot.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_ProbeVehicleData_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
