/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_SignalStatusMessage_H_
#define	_carma_j2735_SignalStatusMessage_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_MinuteOfTheYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSecond.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_MsgCount.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SignalStatusList.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_SignalStatusMessage */
typedef struct carma_j2735_SignalStatusMessage {
	carma_j2735_MinuteOfTheYear_t	*timeStamp;	/* OPTIONAL */
	carma_j2735_DSecond_t	 second;
	carma_j2735_DSRC_MsgCount_t	*sequenceNumber;	/* OPTIONAL */
	carma_j2735_SignalStatusList_t	 status;
	struct carma_j2735_SignalStatusMessage__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_SignalStatusMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_SignalStatusMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_SignalStatusMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_SignalStatusMessage_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_SignalStatusMessage_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
