/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ConfidenceSet_H_
#define	_carma_j2735_ConfidenceSet_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_TimeConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringWheelAngleConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_HeadingConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ThrottleConfidence.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_AccelSteerYawRateConfidence;
struct carma_j2735_SpeedandHeadingandThrottleConfidence;
struct carma_j2735_PositionConfidenceSet;

/* carma_j2735_ConfidenceSet */
typedef struct carma_j2735_ConfidenceSet {
	struct carma_j2735_AccelSteerYawRateConfidence	*accelConfidence;	/* OPTIONAL */
	struct carma_j2735_SpeedandHeadingandThrottleConfidence	*speedConfidence;	/* OPTIONAL */
	carma_j2735_TimeConfidence_t	*timeConfidence;	/* OPTIONAL */
	struct carma_j2735_PositionConfidenceSet	*posConfidence;	/* OPTIONAL */
	carma_j2735_SteeringWheelAngleConfidence_t	*steerConfidence;	/* OPTIONAL */
	carma_j2735_HeadingConfidence_t	*headingConfidence;	/* OPTIONAL */
	carma_j2735_ThrottleConfidence_t	*throttleConfidence;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ConfidenceSet_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ConfidenceSet;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_ConfidenceSet_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ConfidenceSet_1[7];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_AccelSteerYawRateConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpeedandHeadingandThrottleConfidence.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PositionConfidenceSet.h"

#endif	/* _carma_j2735_ConfidenceSet_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
