/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_DDate_H_
#define	_carma_j2735_DDate_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DMonth.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DDay.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_DDate */
typedef struct carma_j2735_DDate {
	carma_j2735_DYear_t	 year;
	carma_j2735_DMonth_t	 month;
	carma_j2735_DDay_t	 day;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_DDate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_DDate;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_DDate_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
