/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_FuelType_H_
#define	_carma_j2735_FuelType_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_FuelType */
typedef long	 carma_j2735_FuelType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_FuelType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_FuelType;
asn_struct_free_f carma_j2735_FuelType_free;
asn_struct_print_f carma_j2735_FuelType_print;
asn_constr_check_f carma_j2735_FuelType_constraint;
per_type_decoder_f carma_j2735_FuelType_decode_uper;
per_type_encoder_f carma_j2735_FuelType_encode_uper;
per_type_decoder_f carma_j2735_FuelType_decode_aper;
per_type_encoder_f carma_j2735_FuelType_encode_aper;
#define carma_j2735_FuelType_unknownFuel	((carma_j2735_FuelType_t)0)
#define carma_j2735_FuelType_gasoline	((carma_j2735_FuelType_t)1)
#define carma_j2735_FuelType_ethanol	((carma_j2735_FuelType_t)2)
#define carma_j2735_FuelType_diesel	((carma_j2735_FuelType_t)3)
#define carma_j2735_FuelType_electric	((carma_j2735_FuelType_t)4)
#define carma_j2735_FuelType_hybrid	((carma_j2735_FuelType_t)5)
#define carma_j2735_FuelType_hydrogen	((carma_j2735_FuelType_t)6)
#define carma_j2735_FuelType_natGasLiquid	((carma_j2735_FuelType_t)7)
#define carma_j2735_FuelType_natGasComp	((carma_j2735_FuelType_t)8)
#define carma_j2735_FuelType_propane	((carma_j2735_FuelType_t)9)

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_FuelType_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
