/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_SegmentAttributeLL_H_
#define	_carma_j2735_SegmentAttributeLL_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_SegmentAttributeLL {
	carma_j2735_SegmentAttributeLL_reserved	= 0,
	carma_j2735_SegmentAttributeLL_doNotBlock	= 1,
	carma_j2735_SegmentAttributeLL_whiteLine	= 2,
	carma_j2735_SegmentAttributeLL_mergingLaneLeft	= 3,
	carma_j2735_SegmentAttributeLL_mergingLaneRight	= 4,
	carma_j2735_SegmentAttributeLL_curbOnLeft	= 5,
	carma_j2735_SegmentAttributeLL_curbOnRight	= 6,
	carma_j2735_SegmentAttributeLL_loadingzoneOnLeft	= 7,
	carma_j2735_SegmentAttributeLL_loadingzoneOnRight	= 8,
	carma_j2735_SegmentAttributeLL_turnOutPointOnLeft	= 9,
	carma_j2735_SegmentAttributeLL_turnOutPointOnRight	= 10,
	carma_j2735_SegmentAttributeLL_adjacentParkingOnLeft	= 11,
	carma_j2735_SegmentAttributeLL_adjacentParkingOnRight	= 12,
	carma_j2735_SegmentAttributeLL_adjacentBikeLaneOnLeft	= 13,
	carma_j2735_SegmentAttributeLL_adjacentBikeLaneOnRight	= 14,
	carma_j2735_SegmentAttributeLL_sharedBikeLane	= 15,
	carma_j2735_SegmentAttributeLL_bikeBoxInFront	= 16,
	carma_j2735_SegmentAttributeLL_transitStopOnLeft	= 17,
	carma_j2735_SegmentAttributeLL_transitStopOnRight	= 18,
	carma_j2735_SegmentAttributeLL_transitStopInLane	= 19,
	carma_j2735_SegmentAttributeLL_sharedWithTrackedVehicle	= 20,
	carma_j2735_SegmentAttributeLL_safeIsland	= 21,
	carma_j2735_SegmentAttributeLL_lowCurbsPresent	= 22,
	carma_j2735_SegmentAttributeLL_rumbleStripPresent	= 23,
	carma_j2735_SegmentAttributeLL_audibleSignalingPresent	= 24,
	carma_j2735_SegmentAttributeLL_adaptiveTimingPresent	= 25,
	carma_j2735_SegmentAttributeLL_rfSignalRequestPresent	= 26,
	carma_j2735_SegmentAttributeLL_partialCurbIntrusion	= 27,
	carma_j2735_SegmentAttributeLL_taperToLeft	= 28,
	carma_j2735_SegmentAttributeLL_taperToRight	= 29,
	carma_j2735_SegmentAttributeLL_taperToCenterLine	= 30,
	carma_j2735_SegmentAttributeLL_parallelParking	= 31,
	carma_j2735_SegmentAttributeLL_headInParking	= 32,
	carma_j2735_SegmentAttributeLL_freeParking	= 33,
	carma_j2735_SegmentAttributeLL_timeRestrictionsOnParking	= 34,
	carma_j2735_SegmentAttributeLL_costToPark	= 35,
	carma_j2735_SegmentAttributeLL_midBlockCurbPresent	= 36,
	carma_j2735_SegmentAttributeLL_unEvenPavementPresent	= 37
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_SegmentAttributeLL;

/* carma_j2735_SegmentAttributeLL */
typedef long	 carma_j2735_SegmentAttributeLL_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_SegmentAttributeLL_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_SegmentAttributeLL;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_SegmentAttributeLL_specs_1;
asn_struct_free_f carma_j2735_SegmentAttributeLL_free;
asn_struct_print_f carma_j2735_SegmentAttributeLL_print;
asn_constr_check_f carma_j2735_SegmentAttributeLL_constraint;
per_type_decoder_f carma_j2735_SegmentAttributeLL_decode_uper;
per_type_encoder_f carma_j2735_SegmentAttributeLL_encode_uper;
per_type_decoder_f carma_j2735_SegmentAttributeLL_decode_aper;
per_type_encoder_f carma_j2735_SegmentAttributeLL_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_SegmentAttributeLL_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
