/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ApproachOrLane_H_
#define	_carma_j2735_ApproachOrLane_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_ApproachID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneID.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ApproachOrLane_PR {
	carma_j2735_ApproachOrLane_PR_NOTHING,	/* No components present */
	carma_j2735_ApproachOrLane_PR_approach,
	carma_j2735_ApproachOrLane_PR_lane
} carma_j2735_ApproachOrLane_PR;

/* carma_j2735_ApproachOrLane */
typedef struct carma_j2735_ApproachOrLane {
	carma_j2735_ApproachOrLane_PR present;
	union carma_j2735_ApproachOrLane_u {
		carma_j2735_ApproachID_t	 approach;
		carma_j2735_LaneID_t	 lane;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ApproachOrLane_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ApproachOrLane;
extern asn_CHOICE_specifics_t asn_SPC_carma_j2735_ApproachOrLane_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ApproachOrLane_1[2];
extern asn_per_constraints_t asn_PER_type_carma_j2735_ApproachOrLane_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_ApproachOrLane_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
