/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_AddGrpB_TimeMark_H_
#define	_carma_j2735_AddGrpB_TimeMark_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_Year.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Month.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Day.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SummerTime.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Holiday.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DayOfWeek.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Hour.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Minute.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Second.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TenthSecond.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_AddGrpB_TimeMark */
typedef struct carma_j2735_AddGrpB_TimeMark {
	carma_j2735_Year_t	 year;
	carma_j2735_Month_t	 month;
	carma_j2735_Day_t	 day;
	carma_j2735_SummerTime_t	 summerTime;
	carma_j2735_Holiday_t	 holiday;
	carma_j2735_DayOfWeek_t	 dayofWeek;
	carma_j2735_Hour_t	 hour;
	carma_j2735_Minute_t	 minute;
	carma_j2735_Second_t	 second;
	carma_j2735_TenthSecond_t	 tenthSecond;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_AddGrpB_TimeMark_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_AddGrpB_TimeMark;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_AddGrpB_TimeMark_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
