/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PartIIcontent_H_
#define	_carma_j2735_PartIIcontent_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_PartII-Id.h"
#include <etsi_its_carma_j2735_coding/ANY.h>
#include <etsi_its_carma_j2735_coding/asn_ioc.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleSafetyExtensions.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpecialVehicleExtensions.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SupplementalVehicleExtensions.h"
#include <etsi_its_carma_j2735_coding/OPEN_TYPE.h>
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_BSMpartIIExtension__partII_Value_PR {
	carma_j2735_BSMpartIIExtension__partII_Value_PR_NOTHING,	/* No components present */
	carma_j2735_BSMpartIIExtension__partII_Value_PR_VehicleSafetyExtensions,
	carma_j2735_BSMpartIIExtension__partII_Value_PR_SpecialVehicleExtensions,
	carma_j2735_BSMpartIIExtension__partII_Value_PR_SupplementalVehicleExtensions
} carma_j2735_BSMpartIIExtension__partII_Value_PR;

/* carma_j2735_PartIIcontent */
typedef struct carma_j2735_BSMpartIIExtension {
	carma_j2735_PartII_Id_t	 partII_Id;
	struct carma_j2735_BSMpartIIExtension__partII_Value {
		carma_j2735_BSMpartIIExtension__partII_Value_PR present;
		union carma_j2735_BSMpartIIExtension__carma_j2735_partII_Value_u {
			carma_j2735_VehicleSafetyExtensions_t	 VehicleSafetyExtensions;
			carma_j2735_SpecialVehicleExtensions_t	 SpecialVehicleExtensions;
			carma_j2735_SupplementalVehicleExtensions_t	 SupplementalVehicleExtensions;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} partII_Value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_BSMpartIIExtension_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_BSMpartIIExtension;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_BSMpartIIExtension_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_BSMpartIIExtension_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_PartIIcontent_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
