/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_LaneAttributes_H_
#define	_carma_j2735_LaneAttributes_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneDirection.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneSharing.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneTypeAttributes.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_LaneAttributes */
typedef struct carma_j2735_LaneAttributes {
	carma_j2735_LaneDirection_t	 directionalUse;
	carma_j2735_LaneSharing_t	 sharedWith;
	carma_j2735_LaneTypeAttributes_t	 laneType;
	struct carma_j2735_Reg_BasicSafetyMessage	*regional;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_LaneAttributes_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_LaneAttributes;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_LaneAttributes_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_LaneAttributes_1[4];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_LaneAttributes_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
