/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VehicleIdent_H_
#define	_carma_j2735_VehicleIdent_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DescriptiveName.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VINstring.h"
#include <etsi_its_carma_j2735_coding/IA5String.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleGroupAffected.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ResponderGroupAffected.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_IncidentResponseEquipment.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_VehicleIdent__vehicleClass_PR {
	carma_j2735_VehicleIdent__vehicleClass_PR_NOTHING,	/* No components present */
	carma_j2735_VehicleIdent__vehicleClass_PR_vGroup,
	carma_j2735_VehicleIdent__vehicleClass_PR_rGroup,
	carma_j2735_VehicleIdent__vehicleClass_PR_rEquip
} carma_j2735_VehicleIdent__vehicleClass_PR;

/* Forward declarations */
struct carma_j2735_VehicleID;

/* carma_j2735_VehicleIdent */
typedef struct carma_j2735_VehicleIdent {
	carma_j2735_DescriptiveName_t	*name;	/* OPTIONAL */
	carma_j2735_VINstring_t	*vin;	/* OPTIONAL */
	IA5String_t	*ownerCode;	/* OPTIONAL */
	struct carma_j2735_VehicleID	*id;	/* OPTIONAL */
	carma_j2735_VehicleType_t	*vehicleType;	/* OPTIONAL */
	struct carma_j2735_VehicleIdent__vehicleClass {
		carma_j2735_VehicleIdent__vehicleClass_PR present;
		union carma_j2735_VehicleIdent__carma_j2735_vehicleClass_u {
			carma_j2735_VehicleGroupAffected_t	 vGroup;
			carma_j2735_ResponderGroupAffected_t	 rGroup;
			carma_j2735_IncidentResponseEquipment_t	 rEquip;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *vehicleClass;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_VehicleIdent_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VehicleIdent;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_VehicleIdent_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_VehicleIdent_1[6];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleID.h"

#endif	/* _carma_j2735_VehicleIdent_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
