/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ElevationConfidence_H_
#define	_carma_j2735_ElevationConfidence_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ElevationConfidence {
	carma_j2735_ElevationConfidence_unavailable	= 0,
	carma_j2735_ElevationConfidence_elev_500_00	= 1,
	carma_j2735_ElevationConfidence_elev_200_00	= 2,
	carma_j2735_ElevationConfidence_elev_100_00	= 3,
	carma_j2735_ElevationConfidence_elev_050_00	= 4,
	carma_j2735_ElevationConfidence_elev_020_00	= 5,
	carma_j2735_ElevationConfidence_elev_010_00	= 6,
	carma_j2735_ElevationConfidence_elev_005_00	= 7,
	carma_j2735_ElevationConfidence_elev_002_00	= 8,
	carma_j2735_ElevationConfidence_elev_001_00	= 9,
	carma_j2735_ElevationConfidence_elev_000_50	= 10,
	carma_j2735_ElevationConfidence_elev_000_20	= 11,
	carma_j2735_ElevationConfidence_elev_000_10	= 12,
	carma_j2735_ElevationConfidence_elev_000_05	= 13,
	carma_j2735_ElevationConfidence_elev_000_02	= 14,
	carma_j2735_ElevationConfidence_elev_000_01	= 15
} e_carma_j2735_ElevationConfidence;

/* carma_j2735_ElevationConfidence */
typedef long	 carma_j2735_ElevationConfidence_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_ElevationConfidence_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ElevationConfidence;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_ElevationConfidence_specs_1;
asn_struct_free_f carma_j2735_ElevationConfidence_free;
asn_struct_print_f carma_j2735_ElevationConfidence_print;
asn_constr_check_f carma_j2735_ElevationConfidence_constraint;
per_type_decoder_f carma_j2735_ElevationConfidence_decode_uper;
per_type_encoder_f carma_j2735_ElevationConfidence_encode_uper;
per_type_decoder_f carma_j2735_ElevationConfidence_decode_aper;
per_type_encoder_f carma_j2735_ElevationConfidence_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_ElevationConfidence_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
