/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_AuxiliaryBrakeStatus_H_
#define	_carma_j2735_AuxiliaryBrakeStatus_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_AuxiliaryBrakeStatus {
	carma_j2735_AuxiliaryBrakeStatus_unavailable	= 0,
	carma_j2735_AuxiliaryBrakeStatus_off	= 1,
	carma_j2735_AuxiliaryBrakeStatus_on	= 2,
	carma_j2735_AuxiliaryBrakeStatus_reserved	= 3
} e_carma_j2735_AuxiliaryBrakeStatus;

/* carma_j2735_AuxiliaryBrakeStatus */
typedef long	 carma_j2735_AuxiliaryBrakeStatus_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_AuxiliaryBrakeStatus_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_AuxiliaryBrakeStatus;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_AuxiliaryBrakeStatus_specs_1;
asn_struct_free_f carma_j2735_AuxiliaryBrakeStatus_free;
asn_struct_print_f carma_j2735_AuxiliaryBrakeStatus_print;
asn_constr_check_f carma_j2735_AuxiliaryBrakeStatus_constraint;
per_type_decoder_f carma_j2735_AuxiliaryBrakeStatus_decode_uper;
per_type_encoder_f carma_j2735_AuxiliaryBrakeStatus_encode_uper;
per_type_decoder_f carma_j2735_AuxiliaryBrakeStatus_decode_aper;
per_type_encoder_f carma_j2735_AuxiliaryBrakeStatus_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_AuxiliaryBrakeStatus_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
