/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_GenericSignage_H_
#define	_carma_j2735_GenericSignage_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_ITIScodes.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ITIStextPhrase.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_GenericSignage__Member__item_PR {
	carma_j2735_GenericSignage__Member__item_PR_NOTHING,	/* No components present */
	carma_j2735_GenericSignage__Member__item_PR_itis,
	carma_j2735_GenericSignage__Member__item_PR_text
} carma_j2735_GenericSignage__Member__item_PR;

/* Forward definitions */
typedef struct carma_j2735_GenericSignage__Member {
	struct carma_j2735_GenericSignage__Member__item {
		carma_j2735_GenericSignage__Member__item_PR present;
		union carma_j2735_GenericSignage__carma_j2735_Member__carma_j2735_item_u {
			carma_j2735_ITIScodes_t	 itis;
			carma_j2735_ITIStextPhrase_t	 text;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} item;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GenericSignage__Member;

/* carma_j2735_GenericSignage */
typedef struct carma_j2735_GenericSignage {
	A_SEQUENCE_OF(GenericSignage__Member) list;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_GenericSignage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_GenericSignage;
extern asn_SET_OF_specifics_t asn_SPC_carma_j2735_GenericSignage_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_GenericSignage_1[1];
extern asn_per_constraints_t asn_PER_type_carma_j2735_GenericSignage_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_GenericSignage_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
