/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ValidRegion_H_
#define	_carma_j2735_ValidRegion_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_HeadingSlice.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Extent.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ShapePointSet.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Circle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionPointSet.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ValidRegion__area_PR {
	carma_j2735_ValidRegion__area_PR_NOTHING,	/* No components present */
	carma_j2735_ValidRegion__area_PR_shapePointSet,
	carma_j2735_ValidRegion__area_PR_circle,
	carma_j2735_ValidRegion__area_PR_regionPointSet
} carma_j2735_ValidRegion__area_PR;

/* carma_j2735_ValidRegion */
typedef struct carma_j2735_ValidRegion {
	carma_j2735_HeadingSlice_t	 direction;
	carma_j2735_Extent_t	*extent;	/* OPTIONAL */
	struct carma_j2735_ValidRegion__area {
		carma_j2735_ValidRegion__area_PR present;
		union carma_j2735_ValidRegion__carma_j2735_area_u {
			carma_j2735_ShapePointSet_t	 shapePointSet;
			carma_j2735_Circle_t	 circle;
			carma_j2735_RegionPointSet_t	 regionPointSet;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} area;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_ValidRegion_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ValidRegion;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_ValidRegion_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_ValidRegion_1[3];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_ValidRegion_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
