/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_BSMcoreData_H_
#define	_carma_j2735_BSMcoreData_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_MsgCount.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TemporaryID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSecond.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Latitude.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Longitude.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_Elevation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PositionalAccuracy.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TransmissionState.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Speed.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Heading.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SteeringWheelAngle.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AccelerationSet4Way.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_BrakeSystemStatus.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_VehicleSize.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_BSMcoreData */
typedef struct carma_j2735_BSMcoreData {
	carma_j2735_DSRC_MsgCount_t	 msgCnt;
	carma_j2735_TemporaryID_t	 id;
	carma_j2735_DSecond_t	 secMark;
	carma_j2735_Latitude_t	 lat;
	carma_j2735_Longitude_t	 Long;
	carma_j2735_DSRC_Elevation_t	 elev;
	carma_j2735_PositionalAccuracy_t	 accuracy;
	carma_j2735_TransmissionState_t	 transmission;
	carma_j2735_Speed_t	 speed;
	carma_j2735_Heading_t	 heading;
	carma_j2735_SteeringWheelAngle_t	 angle;
	carma_j2735_AccelerationSet4Way_t	 accelSet;
	carma_j2735_BrakeSystemStatus_t	 brakes;
	carma_j2735_VehicleSize_t	 size;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_BSMcoreData_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_BSMcoreData;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_BSMcoreData_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_BSMcoreData_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_BSMcoreData_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
