/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_Connection_H_
#define	_carma_j2735_Connection_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_ConnectingLane.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SignalGroupID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RestrictionClassID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_LaneConnectionID.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_IntersectionReferenceID;

/* carma_j2735_Connection */
typedef struct carma_j2735_Connection {
	carma_j2735_ConnectingLane_t	 connectingLane;
	struct carma_j2735_IntersectionReferenceID	*remoteIntersection;	/* OPTIONAL */
	carma_j2735_SignalGroupID_t	*signalGroup;	/* OPTIONAL */
	carma_j2735_RestrictionClassID_t	*userClass;	/* OPTIONAL */
	carma_j2735_LaneConnectionID_t	*connectionID;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_Connection_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_Connection;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_Connection_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_Connection_1[5];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_IntersectionReferenceID.h"

#endif	/* _carma_j2735_Connection_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
