/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_VehicleGroupAffected_H_
#define	_carma_j2735_VehicleGroupAffected_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_VehicleGroupAffected {
	carma_j2735_VehicleGroupAffected_all_vehicles	= 9217,
	carma_j2735_VehicleGroupAffected_bicycles	= 9218,
	carma_j2735_VehicleGroupAffected_motorcycles	= 9219,
	carma_j2735_VehicleGroupAffected_cars	= 9220,
	carma_j2735_VehicleGroupAffected_light_vehicles	= 9221,
	carma_j2735_VehicleGroupAffected_cars_and_light_vehicles	= 9222,
	carma_j2735_VehicleGroupAffected_cars_with_trailers	= 9223,
	carma_j2735_VehicleGroupAffected_cars_with_recreational_trailers	= 9224,
	carma_j2735_VehicleGroupAffected_vehicles_with_trailers	= 9225,
	carma_j2735_VehicleGroupAffected_heavy_vehicles	= 9226,
	carma_j2735_VehicleGroupAffected_trucks	= 9227,
	carma_j2735_VehicleGroupAffected_buses	= 9228,
	carma_j2735_VehicleGroupAffected_articulated_buses	= 9229,
	carma_j2735_VehicleGroupAffected_school_buses	= 9230,
	carma_j2735_VehicleGroupAffected_vehicles_with_semi_trailers	= 9231,
	carma_j2735_VehicleGroupAffected_vehicles_with_double_trailers	= 9232,
	carma_j2735_VehicleGroupAffected_high_profile_vehicles	= 9233,
	carma_j2735_VehicleGroupAffected_wide_vehicles	= 9234,
	carma_j2735_VehicleGroupAffected_long_vehicles	= 9235,
	carma_j2735_VehicleGroupAffected_hazardous_loads	= 9236,
	carma_j2735_VehicleGroupAffected_exceptional_loads	= 9237,
	carma_j2735_VehicleGroupAffected_abnormal_loads	= 9238,
	carma_j2735_VehicleGroupAffected_convoys	= 9239,
	carma_j2735_VehicleGroupAffected_maintenance_vehicles	= 9240,
	carma_j2735_VehicleGroupAffected_delivery_vehicles	= 9241,
	carma_j2735_VehicleGroupAffected_vehicles_with_even_numbered_license_plates	= 9242,
	carma_j2735_VehicleGroupAffected_vehicles_with_odd_numbered_license_plates	= 9243,
	carma_j2735_VehicleGroupAffected_vehicles_with_parking_permits	= 9244,
	carma_j2735_VehicleGroupAffected_vehicles_with_catalytic_converters	= 9245,
	carma_j2735_VehicleGroupAffected_vehicles_without_catalytic_converters	= 9246,
	carma_j2735_VehicleGroupAffected_gas_powered_vehicles	= 9247,
	carma_j2735_VehicleGroupAffected_diesel_powered_vehicles	= 9248,
	carma_j2735_VehicleGroupAffected_lPG_vehicles	= 9249,
	carma_j2735_VehicleGroupAffected_military_convoys	= 9250,
	carma_j2735_VehicleGroupAffected_military_vehicles	= 9251
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_VehicleGroupAffected;

/* carma_j2735_VehicleGroupAffected */
typedef long	 carma_j2735_VehicleGroupAffected_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_VehicleGroupAffected_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_VehicleGroupAffected;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_VehicleGroupAffected_specs_1;
asn_struct_free_f carma_j2735_VehicleGroupAffected_free;
asn_struct_print_f carma_j2735_VehicleGroupAffected_print;
asn_constr_check_f carma_j2735_VehicleGroupAffected_constraint;
per_type_decoder_f carma_j2735_VehicleGroupAffected_decode_uper;
per_type_encoder_f carma_j2735_VehicleGroupAffected_encode_uper;
per_type_decoder_f carma_j2735_VehicleGroupAffected_decode_aper;
per_type_encoder_f carma_j2735_VehicleGroupAffected_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_VehicleGroupAffected_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
