/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITIS"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_IncidentResponseEquipment_H_
#define	_carma_j2735_IncidentResponseEquipment_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_IncidentResponseEquipment {
	carma_j2735_IncidentResponseEquipment_ground_fire_suppression	= 9985,
	carma_j2735_IncidentResponseEquipment_heavy_ground_equipment	= 9986,
	carma_j2735_IncidentResponseEquipment_aircraft	= 9988,
	carma_j2735_IncidentResponseEquipment_marine_equipment	= 9989,
	carma_j2735_IncidentResponseEquipment_support_equipment	= 9990,
	carma_j2735_IncidentResponseEquipment_medical_rescue_unit	= 9991,
	carma_j2735_IncidentResponseEquipment_other	= 9993,
	carma_j2735_IncidentResponseEquipment_ground_fire_suppression_other	= 9994,
	carma_j2735_IncidentResponseEquipment_engine	= 9995,
	carma_j2735_IncidentResponseEquipment_truck_or_aerial	= 9996,
	carma_j2735_IncidentResponseEquipment_quint	= 9997,
	carma_j2735_IncidentResponseEquipment_tanker_pumper_combination	= 9998,
	carma_j2735_IncidentResponseEquipment_brush_truck	= 10000,
	carma_j2735_IncidentResponseEquipment_aircraft_rescue_firefighting	= 10001,
	carma_j2735_IncidentResponseEquipment_heavy_ground_equipment_other	= 10004,
	carma_j2735_IncidentResponseEquipment_dozer_or_plow	= 10005,
	carma_j2735_IncidentResponseEquipment_tractor	= 10006,
	carma_j2735_IncidentResponseEquipment_tanker_or_tender	= 10008,
	carma_j2735_IncidentResponseEquipment_aircraft_other	= 10024,
	carma_j2735_IncidentResponseEquipment_aircraft_fixed_wing_tanker	= 10025,
	carma_j2735_IncidentResponseEquipment_helitanker	= 10026,
	carma_j2735_IncidentResponseEquipment_helicopter	= 10027,
	carma_j2735_IncidentResponseEquipment_marine_equipment_other	= 10034,
	carma_j2735_IncidentResponseEquipment_fire_boat_with_pump	= 10035,
	carma_j2735_IncidentResponseEquipment_boat_no_pump	= 10036,
	carma_j2735_IncidentResponseEquipment_support_apparatus_other	= 10044,
	carma_j2735_IncidentResponseEquipment_breathing_apparatus_support	= 10045,
	carma_j2735_IncidentResponseEquipment_light_and_air_unit	= 10046,
	carma_j2735_IncidentResponseEquipment_medical_rescue_unit_other	= 10054,
	carma_j2735_IncidentResponseEquipment_rescue_unit	= 10055,
	carma_j2735_IncidentResponseEquipment_urban_search_rescue_unit	= 10056,
	carma_j2735_IncidentResponseEquipment_high_angle_rescue	= 10057,
	carma_j2735_IncidentResponseEquipment_crash_fire_rescue	= 10058,
	carma_j2735_IncidentResponseEquipment_bLS_unit	= 10059,
	carma_j2735_IncidentResponseEquipment_aLS_unit	= 10060,
	carma_j2735_IncidentResponseEquipment_mobile_command_post	= 10075,
	carma_j2735_IncidentResponseEquipment_chief_officer_car	= 10076,
	carma_j2735_IncidentResponseEquipment_hAZMAT_unit	= 10077,
	carma_j2735_IncidentResponseEquipment_type_i_hand_crew	= 10078,
	carma_j2735_IncidentResponseEquipment_type_ii_hand_crew	= 10079,
	carma_j2735_IncidentResponseEquipment_privately_owned_vehicle	= 10083,
	carma_j2735_IncidentResponseEquipment_other_apparatus_resource	= 10084,
	carma_j2735_IncidentResponseEquipment_ambulance	= 10085,
	carma_j2735_IncidentResponseEquipment_bomb_squad_van	= 10086,
	carma_j2735_IncidentResponseEquipment_combine_harvester	= 10087,
	carma_j2735_IncidentResponseEquipment_construction_vehicle	= 10088,
	carma_j2735_IncidentResponseEquipment_farm_tractor	= 10089,
	carma_j2735_IncidentResponseEquipment_grass_cutting_machines	= 10090,
	carma_j2735_IncidentResponseEquipment_hAZMAT_containment_tow	= 10091,
	carma_j2735_IncidentResponseEquipment_heavy_tow	= 10092,
	carma_j2735_IncidentResponseEquipment_light_tow	= 10094,
	carma_j2735_IncidentResponseEquipment_flatbed_tow	= 10114,
	carma_j2735_IncidentResponseEquipment_hedge_cutting_machines	= 10093,
	carma_j2735_IncidentResponseEquipment_mobile_crane	= 10095,
	carma_j2735_IncidentResponseEquipment_refuse_collection_vehicle	= 10096,
	carma_j2735_IncidentResponseEquipment_resurfacing_vehicle	= 10097,
	carma_j2735_IncidentResponseEquipment_road_sweeper	= 10098,
	carma_j2735_IncidentResponseEquipment_roadside_litter_collection_crews	= 10099,
	carma_j2735_IncidentResponseEquipment_salvage_vehicle	= 10100,
	carma_j2735_IncidentResponseEquipment_sand_truck	= 10101,
	carma_j2735_IncidentResponseEquipment_snowplow	= 10102,
	carma_j2735_IncidentResponseEquipment_steam_roller	= 10103,
	carma_j2735_IncidentResponseEquipment_swat_team_van	= 10104,
	carma_j2735_IncidentResponseEquipment_track_laying_vehicle	= 10105,
	carma_j2735_IncidentResponseEquipment_unknown_vehicle	= 10106,
	carma_j2735_IncidentResponseEquipment_white_lining_vehicle	= 10107,
	carma_j2735_IncidentResponseEquipment_dump_truck	= 10108,
	carma_j2735_IncidentResponseEquipment_supervisor_vehicle	= 10109,
	carma_j2735_IncidentResponseEquipment_snow_blower	= 10110,
	carma_j2735_IncidentResponseEquipment_rotary_snow_blower	= 10111,
	carma_j2735_IncidentResponseEquipment_road_grader	= 10112,
	carma_j2735_IncidentResponseEquipment_steam_truck	= 10113
	/*
	 * Enumeration is extensible
	 */
} e_carma_j2735_IncidentResponseEquipment;

/* carma_j2735_IncidentResponseEquipment */
typedef long	 carma_j2735_IncidentResponseEquipment_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_IncidentResponseEquipment_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_IncidentResponseEquipment;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_IncidentResponseEquipment_specs_1;
asn_struct_free_f carma_j2735_IncidentResponseEquipment_free;
asn_struct_print_f carma_j2735_IncidentResponseEquipment_print;
asn_constr_check_f carma_j2735_IncidentResponseEquipment_constraint;
per_type_decoder_f carma_j2735_IncidentResponseEquipment_decode_uper;
per_type_encoder_f carma_j2735_IncidentResponseEquipment_encode_uper;
per_type_decoder_f carma_j2735_IncidentResponseEquipment_decode_aper;
per_type_encoder_f carma_j2735_IncidentResponseEquipment_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_IncidentResponseEquipment_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
