/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_RequestImportanceLevel_H_
#define	_carma_j2735_RequestImportanceLevel_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeEnumerated.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_RequestImportanceLevel {
	carma_j2735_RequestImportanceLevel_requestImportanceLevelUnKnown	= 0,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel1	= 1,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel2	= 2,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel3	= 3,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel4	= 4,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel5	= 5,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel6	= 6,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel7	= 7,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel8	= 8,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel9	= 9,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel10	= 10,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel11	= 11,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel12	= 12,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel13	= 13,
	carma_j2735_RequestImportanceLevel_requestImportanceLevel14	= 14,
	carma_j2735_RequestImportanceLevel_requestImportanceReserved	= 15
} e_carma_j2735_RequestImportanceLevel;

/* carma_j2735_RequestImportanceLevel */
typedef long	 carma_j2735_RequestImportanceLevel_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_RequestImportanceLevel_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_RequestImportanceLevel;
extern const asn_INTEGER_specifics_t asn_SPC_carma_j2735_RequestImportanceLevel_specs_1;
asn_struct_free_f carma_j2735_RequestImportanceLevel_free;
asn_struct_print_f carma_j2735_RequestImportanceLevel_print;
asn_constr_check_f carma_j2735_RequestImportanceLevel_constraint;
per_type_decoder_f carma_j2735_RequestImportanceLevel_decode_uper;
per_type_encoder_f carma_j2735_RequestImportanceLevel_encode_uper;
per_type_decoder_f carma_j2735_RequestImportanceLevel_decode_aper;
per_type_encoder_f carma_j2735_RequestImportanceLevel_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_RequestImportanceLevel_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
