/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PersonalSafetyMessage_H_
#define	_carma_j2735_PersonalSafetyMessage_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalDeviceUserType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSecond.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DSRC_MsgCount.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TemporaryID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Position3D.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PositionalAccuracy.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Velocity.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Heading.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalDeviceUsageState.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalCrossingRequest.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalCrossingInProgress.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_NumberOfParticipantsInCluster.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalClusterRadius.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PublicSafetyEventResponderWorkerType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PublicSafetyAndRoadWorkerActivity.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PublicSafetyDirectingTrafficSubType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PersonalAssistive.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_UserSizeAndBehaviour.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Attachment.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AttachmentRadius.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_AnimalType.h"
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct carma_j2735_AccelerationSet4Way;
struct carma_j2735_PathHistory;
struct carma_j2735_PathPrediction;
struct carma_j2735_PropelledInformation;
struct carma_j2735_Reg_BasicSafetyMessage;

/* carma_j2735_PersonalSafetyMessage */
typedef struct carma_j2735_PersonalSafetyMessage {
	carma_j2735_PersonalDeviceUserType_t	 basicType;
	carma_j2735_DSecond_t	 secMark;
	carma_j2735_DSRC_MsgCount_t	 msgCnt;
	carma_j2735_TemporaryID_t	 id;
	carma_j2735_Position3D_t	 position;
	carma_j2735_PositionalAccuracy_t	 accuracy;
	carma_j2735_Velocity_t	 speed;
	carma_j2735_Heading_t	 heading;
	struct carma_j2735_AccelerationSet4Way	*accelSet;	/* OPTIONAL */
	struct carma_j2735_PathHistory	*pathHistory;	/* OPTIONAL */
	struct carma_j2735_PathPrediction	*pathPrediction;	/* OPTIONAL */
	struct carma_j2735_PropelledInformation	*propulsion;	/* OPTIONAL */
	carma_j2735_PersonalDeviceUsageState_t	*useState;	/* OPTIONAL */
	carma_j2735_PersonalCrossingRequest_t	*crossRequest;	/* OPTIONAL */
	carma_j2735_PersonalCrossingInProgress_t	*crossState;	/* OPTIONAL */
	carma_j2735_NumberOfParticipantsInCluster_t	*clusterSize;	/* OPTIONAL */
	carma_j2735_PersonalClusterRadius_t	*clusterRadius;	/* OPTIONAL */
	carma_j2735_PublicSafetyEventResponderWorkerType_t	*eventResponderType;	/* OPTIONAL */
	carma_j2735_PublicSafetyAndRoadWorkerActivity_t	*activityType;	/* OPTIONAL */
	carma_j2735_PublicSafetyDirectingTrafficSubType_t	*activitySubType;	/* OPTIONAL */
	carma_j2735_PersonalAssistive_t	*assistType;	/* OPTIONAL */
	carma_j2735_UserSizeAndBehaviour_t	*sizing;	/* OPTIONAL */
	carma_j2735_Attachment_t	*attachment;	/* OPTIONAL */
	carma_j2735_AttachmentRadius_t	*attachmentRadius;	/* OPTIONAL */
	carma_j2735_AnimalType_t	*animalType;	/* OPTIONAL */
	struct carma_j2735_PersonalSafetyMessage__regional {
		A_SEQUENCE_OF(struct carma_j2735_Reg_BasicSafetyMessage) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *regional;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_PersonalSafetyMessage_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_PersonalSafetyMessage;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_PersonalSafetyMessage_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_PersonalSafetyMessage_1[26];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_AccelerationSet4Way.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PathHistory.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PathPrediction.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_PropelledInformation.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"

#endif	/* _carma_j2735_PersonalSafetyMessage_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
