/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_TravelerDataFrame_H_
#define	_carma_j2735_TravelerDataFrame_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_SSPindex.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_TravelerInfoType.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_DYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MinuteOfTheYear.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_MinutesDuration.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SignPrority.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_URL-Short.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_FurtherInfoID.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RoadSignID.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>
#include <etsi_its_carma_j2735_coding/asn_SEQUENCE_OF.h>
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE_OF.h>
#include "etsi_its_carma_j2735_coding/carma_j2735_ITIScodesAndText.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_WorkZone.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_GenericSignage.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_SpeedLimit.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_ExitService.h"
#include <etsi_its_carma_j2735_coding/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_TravelerDataFrame__msgId_PR {
	carma_j2735_TravelerDataFrame__msgId_PR_NOTHING,	/* No components present */
	carma_j2735_TravelerDataFrame__msgId_PR_furtherInfoID,
	carma_j2735_TravelerDataFrame__msgId_PR_roadSignID
} carma_j2735_TravelerDataFrame__msgId_PR;
typedef enum carma_j2735_TravelerDataFrame__content_PR {
	carma_j2735_TravelerDataFrame__content_PR_NOTHING,	/* No components present */
	carma_j2735_TravelerDataFrame__content_PR_advisory,
	carma_j2735_TravelerDataFrame__content_PR_workZone,
	carma_j2735_TravelerDataFrame__content_PR_genericSign,
	carma_j2735_TravelerDataFrame__content_PR_speedLimit,
	carma_j2735_TravelerDataFrame__content_PR_exitService
} carma_j2735_TravelerDataFrame__content_PR;

/* Forward declarations */
struct carma_j2735_GeographicalPath;

/* carma_j2735_TravelerDataFrame */
typedef struct carma_j2735_TravelerDataFrame {
	carma_j2735_SSPindex_t	 sspTimRights;
	carma_j2735_TravelerInfoType_t	 frameType;
	struct carma_j2735_TravelerDataFrame__msgId {
		carma_j2735_TravelerDataFrame__msgId_PR present;
		union carma_j2735_TravelerDataFrame__carma_j2735_msgId_u {
			carma_j2735_FurtherInfoID_t	 furtherInfoID;
			carma_j2735_RoadSignID_t	 roadSignID;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} msgId;
	carma_j2735_DYear_t	*startYear;	/* OPTIONAL */
	carma_j2735_MinuteOfTheYear_t	 startTime;
	carma_j2735_MinutesDuration_t	 duratonTime;
	carma_j2735_SignPrority_t	 priority;
	carma_j2735_SSPindex_t	 sspLocationRights;
	struct carma_j2735_TravelerDataFrame__regions {
		A_SEQUENCE_OF(struct carma_j2735_GeographicalPath) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} regions;
	carma_j2735_SSPindex_t	 sspMsgRights1;
	carma_j2735_SSPindex_t	 sspMsgRights2;
	struct carma_j2735_TravelerDataFrame__content {
		carma_j2735_TravelerDataFrame__content_PR present;
		union carma_j2735_TravelerDataFrame__carma_j2735_content_u {
			carma_j2735_ITIScodesAndText_t	 advisory;
			carma_j2735_WorkZone_t	 workZone;
			carma_j2735_GenericSignage_t	 genericSign;
			carma_j2735_SpeedLimit_t	 speedLimit;
			carma_j2735_ExitService_t	 exitService;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} content;
	carma_j2735_URL_Short_t	*url;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_TravelerDataFrame_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_TravelerDataFrame;
extern asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_TravelerDataFrame_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_TravelerDataFrame_1[13];

#ifdef __cplusplus
}
#endif

/* Referred external types */
#include "etsi_its_carma_j2735_coding/carma_j2735_GeographicalPath.h"

#endif	/* _carma_j2735_TravelerDataFrame_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
