/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_ExteriorLights_H_
#define	_carma_j2735_ExteriorLights_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/BIT_STRING.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_ExteriorLights {
	carma_j2735_ExteriorLights_lowBeamHeadlightsOn	= 0,
	carma_j2735_ExteriorLights_highBeamHeadlightsOn	= 1,
	carma_j2735_ExteriorLights_leftTurnSignalOn	= 2,
	carma_j2735_ExteriorLights_rightTurnSignalOn	= 3,
	carma_j2735_ExteriorLights_hazardSignalOn	= 4,
	carma_j2735_ExteriorLights_automaticLightControlOn	= 5,
	carma_j2735_ExteriorLights_daytimeRunningLightsOn	= 6,
	carma_j2735_ExteriorLights_fogLightOn	= 7,
	carma_j2735_ExteriorLights_parkingLightsOn	= 8
} e_carma_j2735_ExteriorLights;

/* carma_j2735_ExteriorLights */
typedef BIT_STRING_t	 carma_j2735_ExteriorLights_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_ExteriorLights_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_ExteriorLights;
asn_struct_free_f carma_j2735_ExteriorLights_free;
asn_struct_print_f carma_j2735_ExteriorLights_print;
asn_constr_check_f carma_j2735_ExteriorLights_constraint;
per_type_decoder_f carma_j2735_ExteriorLights_decode_uper;
per_type_encoder_f carma_j2735_ExteriorLights_encode_uper;
per_type_decoder_f carma_j2735_ExteriorLights_decode_aper;
per_type_encoder_f carma_j2735_ExteriorLights_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_ExteriorLights_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
