/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_PartII_Id_H_
#define	_carma_j2735_PartII_Id_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include <etsi_its_carma_j2735_coding/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* carma_j2735_PartII-Id */
typedef long	 carma_j2735_PartII_Id_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_carma_j2735_PartII_Id_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_PartII_Id;
asn_struct_free_f carma_j2735_PartII_Id_free;
asn_struct_print_f carma_j2735_PartII_Id_print;
asn_constr_check_f carma_j2735_PartII_Id_constraint;
per_type_decoder_f carma_j2735_PartII_Id_decode_uper;
per_type_encoder_f carma_j2735_PartII_Id_encode_uper;
per_type_decoder_f carma_j2735_PartII_Id_decode_aper;
per_type_encoder_f carma_j2735_PartII_Id_encode_aper;
#define carma_j2735_PartII_Id_vehicleSafetyExt	((carma_j2735_PartII_Id_t)0)
#define carma_j2735_PartII_Id_specialVehicleExt	((carma_j2735_PartII_Id_t)1)
#define carma_j2735_PartII_Id_supplementalVehicleExt	((carma_j2735_PartII_Id_t)2)

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_PartII_Id_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
