/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "DSRC"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#ifndef	_carma_j2735_NodeOffsetPointXY_H_
#define	_carma_j2735_NodeOffsetPointXY_H_


#include <etsi_its_carma_j2735_coding/asn_application.h>

/* Including external dependencies */
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-20b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-22b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-24b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-26b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-28b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-XY-32b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_Node-LLmD-64b.h"
#include "etsi_its_carma_j2735_coding/carma_j2735_RegionalExtension.h"
#include <etsi_its_carma_j2735_coding/constr_CHOICE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum carma_j2735_NodeOffsetPointXY_PR {
	carma_j2735_NodeOffsetPointXY_PR_NOTHING,	/* No components present */
	carma_j2735_NodeOffsetPointXY_PR_node_XY1,
	carma_j2735_NodeOffsetPointXY_PR_node_XY2,
	carma_j2735_NodeOffsetPointXY_PR_node_XY3,
	carma_j2735_NodeOffsetPointXY_PR_node_XY4,
	carma_j2735_NodeOffsetPointXY_PR_node_XY5,
	carma_j2735_NodeOffsetPointXY_PR_node_XY6,
	carma_j2735_NodeOffsetPointXY_PR_node_LatLon,
	carma_j2735_NodeOffsetPointXY_PR_regional
} carma_j2735_NodeOffsetPointXY_PR;

/* carma_j2735_NodeOffsetPointXY */
typedef struct carma_j2735_NodeOffsetPointXY {
	carma_j2735_NodeOffsetPointXY_PR present;
	union carma_j2735_NodeOffsetPointXY_u {
		carma_j2735_Node_XY_20b_t	 node_XY1;
		carma_j2735_Node_XY_22b_t	 node_XY2;
		carma_j2735_Node_XY_24b_t	 node_XY3;
		carma_j2735_Node_XY_26b_t	 node_XY4;
		carma_j2735_Node_XY_28b_t	 node_XY5;
		carma_j2735_Node_XY_32b_t	 node_XY6;
		carma_j2735_Node_LLmD_64b_t	 node_LatLon;
		carma_j2735_Reg_BasicSafetyMessage_t	 regional;
	} choice;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} carma_j2735_NodeOffsetPointXY_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_carma_j2735_NodeOffsetPointXY;
extern asn_CHOICE_specifics_t asn_SPC_carma_j2735_NodeOffsetPointXY_specs_1;
extern asn_TYPE_member_t asn_MBR_carma_j2735_NodeOffsetPointXY_1[8];
extern asn_per_constraints_t asn_PER_type_carma_j2735_NodeOffsetPointXY_constr_1;

#ifdef __cplusplus
}
#endif

#endif	/* _carma_j2735_NodeOffsetPointXY_H_ */
#include <etsi_its_carma_j2735_coding/asn_internal.h>
