# default:
#   tags: [privileged, amd64]
#   image: docker:24.0.7-git
#   services: [docker:24.0.7-dind]
#   before_script:
#     - apk update
#     - apk add bash python3 py3-pip
#     - pip3 install -r ./utils/codegen/codegen-py/requirements.txt --break-system-packages
#     - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}

# variables:
#   DOCKER_DRIVER: overlay2
#   DOCKER_TLS_CERTDIR: /certs
#   GIT_SUBMODULE_STRATEGY: recursive
#   _ASN1C_CI_IMAGE: ${CI_REGISTRY_IMAGE}/asn1c:${CI_COMMIT_REF_SLUG}_ci
#   _ASN1C_IMAGE_LATEST: ${CI_REGISTRY_IMAGE}/asn1c:latest
#   _RGEN_CI_IMAGE: ${CI_REGISTRY_IMAGE}/rgen:${CI_COMMIT_REF_SLUG}_ci
#   _RGEN_IMAGE_LATEST: ${CI_REGISTRY_IMAGE}/rgen:latest

# stages:
#   - Build Docker Images
#   - asn1c
#   - JSON Schema
#   - Conversion Headers

# asn1c-docker:
#   stage: Build Docker Images
#   before_script:
#     - cd utils/codegen/asn1ToC/docker
#     - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
#   script:
#     - docker build -t ${_ASN1C_CI_IMAGE} -f asn1c.Dockerfile .
#     - docker push ${_ASN1C_CI_IMAGE}
#     - |-
#       if [[ "${CI_COMMIT_REF_SLUG}" == "${CI_DEFAULT_BRANCH}" ]]; then
#         docker tag ${_ASN1C_CI_IMAGE} ${_ASN1C_IMAGE_LATEST}
#         docker push ${_ASN1C_IMAGE_LATEST}
#       fi

# stol_its_carma_j2735_coding:
#   stage: asn1c
#   needs: ["asn1c-docker"]
#   script:
#     - >
#       utils/codegen/asn1ToC/asn1ToC.py
#       asn1/raw/carma_j2735/J2735_201603.asn
#       -t carma_j2735
#       -o stol_its_coding/stol_its_carma_j2735_coding
#       -td /builds/$CI_PROJECT_PATH/tmp
#       -di ${_ASN1C_CI_IMAGE}
#     - rm -rf /builds/$CI_PROJECT_PATH/tmp
#     - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository" && git diff; exit 1; fi

# stol_its_carma_j2735_msgs:
#   stage: JSON Schema
#   script:
#     - >
#       utils/codegen/codegen-py/asn1ToJsonSchema.py
#       asn1/raw/carma_j2735/TestMessage01.asn
#       -t carma_j2735
#       -o stol_its_msgs/stol_its_its_carma_j2735_msgs/msg
#     - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository" && git diff; exit 1; fi

# stol_its_carma_j2735_conversion:
#   stage: Conversion Headers
#   script:
#     - >
#       utils/codegen/codegen-py/asn1ToConversionHeader.py
#       asn1/raw/carma_j2735/TestMessage01.asn
#       -t carma_j2735
#       -o stol_its_conversion/stol_its_carma_j2735_conversion/include/stol_its_ccarma_j2735_conversion
#     - if [[ ! -z "$(git status --porcelain)" ]]; then echo "Code generation script resulted in changes to the repository" && git diff; exit 1; fi