/** ============================================================================
MIT License

Copyright (c) 2023-2025 Institute for Automotive Engineering (ika), RWTH Aachen University

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
============================================================================= */

/** Auto-generated by https://github.com/ika-rwth-aachen/etsi_its_messages -----
python3 \
  utils/codegen/codegen-py/asn1ToConversionHeader.py \
  asn1/raw/carma_j2735/TestMessage01.asn \
  -t \
  carma_j2735 \
  -o \
  etsi_its_conversion/etsi_its_carma_j2735_conversion/include/etsi_its_carma_j2735_conversion
----------------------------------------------------------------------------- */

/** ASN.1 Definition -----------------------------------------------------------
MobilityStaticID ::= IA5String (SIZE(2..16))
----------------------------------------------------------------------------- */

#pragma once

#include <etsi_its_carma_j2735_coding/carma_j2735_MobilityStaticID.h>
#include <etsi_its_carma_j2735_coding/IA5String.h>
#include <etsi_its_primitives_conversion/convertIA5String.h>
#ifdef ROS1
#include <etsi_its_carma_j2735_msgs/MobilityStaticID.h>
namespace carma_j2735_msgs = etsi_its_carma_j2735_msgs;
#else
#include <etsi_its_carma_j2735_msgs/msg/mobility_static_id.hpp>
namespace carma_j2735_msgs = etsi_its_carma_j2735_msgs::msg;
#endif


namespace etsi_its_carma_j2735_conversion {

void toRos_MobilityStaticID(const carma_j2735_MobilityStaticID_t& in, carma_j2735_msgs::MobilityStaticID& out) {
  etsi_its_primitives_conversion::toRos_IA5String(in, out.value);
}

void toStruct_MobilityStaticID(const carma_j2735_msgs::MobilityStaticID& in, carma_j2735_MobilityStaticID_t& out) {
  memset(&out, 0, sizeof(carma_j2735_MobilityStaticID_t));
  etsi_its_primitives_conversion::toStruct_IA5String(in.value, out);
}

}
