/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "AddGrpB"
 * 	found in "/input/J2735_201603.asn"
 * 	`asn1c -fcompound-names -fprefix=carma_j2735_ -no-gen-BER -no-gen-XER -no-gen-JER -no-gen-OER -no-gen-example -gen-UPER`
 */

#include "etsi_its_carma_j2735_coding/carma_j2735_LaneDataAttribute-addGrpB.h"

static const ber_tlv_tag_t asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SEQUENCE_specifics_t asn_SPC_carma_j2735_LaneDataAttribute_addGrpB_specs_1 = {
	sizeof(struct carma_j2735_LaneDataAttribute_addGrpB),
	offsetof(struct carma_j2735_LaneDataAttribute_addGrpB, _asn_ctx),
	0,	/* No top level tags */
	0,	/* No tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	0,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_carma_j2735_LaneDataAttribute_addGrpB = {
	"LaneDataAttribute-addGrpB",
	"LaneDataAttribute-addGrpB",
	&asn_OP_SEQUENCE,
	asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1,
	sizeof(asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1)
		/sizeof(asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1[0]), /* 1 */
	asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1,	/* Same as above */
	sizeof(asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1)
		/sizeof(asn_DEF_carma_j2735_LaneDataAttribute_addGrpB_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_carma_j2735_LaneDataAttribute_addGrpB_specs_1	/* Additional specs */
};

