TestMessage00 DEFINITIONS AUTOMATIC TAGS ::= BEGIN

TestMessage00 ::= SEQUENCE {
   header          MobilityHeader,
   body            MobilityRequest
   }

MobilityECEFCoordinate ::= INTEGER(-638363700..638363700)

MobilityLocation ::= SEQUENCE {
   ecefX           MobilityECEFCoordinate,
   ecefY           MobilityECEFCoordinate,
   ecefZ           MobilityECEFCoordinate,
   timestamp       MobilityTimestamp
}

MobilityPlanType ::= ENUMERATED {
   unknown (0), 
   changingLanesToTheLeft (1), 
   changingLanesToTheRight (2), 
   joinPlatoonAtRear (3),
   platoonFollowerJoin (4)
   }

MobilityRequest ::= SEQUENCE {
   strategy        MobilityStrategy,
   planType        MobilityPlanType,
   urgency         MobilityUrgency,
   location        MobilityLocation,
   strategyParams  MobilityParameters,
   trajectoryStart MobilityLocation OPTIONAL,
   trajectory      MobilityLocationOffsets OPTIONAL,
   expiration      MobilityTimestamp OPTIONAL
}

MobilityDynamicID ::= IA5String (SIZE(8))

MobilityLocationOffsets ::= SEQUENCE (SIZE(0..60)) OF MobilityECEFOffset

MobilityECEFOffset ::= SEQUENCE {
   offsetX         MobilityECEFOffsetCoordinate,
   offsetY         MobilityECEFOffsetCoordinate,
   offsetZ         MobilityECEFOffsetCoordinate
}

MobilityStrategy ::= IA5String (SIZE(2..50))

MobilityTimestamp ::= IA5String (SIZE(19))

MobilityECEFOffsetCoordinate ::= INTEGER(-500..501)

MobilityHeader ::= SEQUENCE {
   hostStaticId    MobilityStaticID,
   targetStaticId  MobilityStaticID,
   hostBSMId       MobilityDynamicID,
   planId          MobilityGUID,
   timestamp       MobilityTimestamp
}

MobilityUrgency ::= INTEGER (0..1000)

MobilityStaticID ::= IA5String (SIZE(2..16))

MobilityGUID ::= IA5String (SIZE(36))

MobilityParameters ::= IA5String (SIZE(2..1000))

END
